import Link from 'next/link';
import {notFound,redirect} from 'next/navigation';
import {PlatformShell,PageHeading} from '@/components/platform-shell';
import {isLocale} from '@/lib/i18n';
import {createSupabaseServerClient} from '@/lib/supabase/server';
import {formatLeaveMinutes,leaveEntryLabel} from '@/lib/workforce-leave-display';
import {leaveOperation} from './actions';
import '../operations/workforce-operations.css';
export default async function Leave({params,searchParams}:{params:Promise<{locale:string}>;searchParams:Promise<{owner?:string;policy?:string;notice?:string}>}) {
  const {locale}=await params;if(!isLocale(locale))notFound();const t=(en:string,es:string)=>locale==='es'?es:en;
  const db=await createSupabaseServerClient();const {data:{user}}=await db.auth.getUser();if(!user)redirect(`/${locale}/sign-in`);
  const query=await searchParams;const owner=query.owner||user.id;const today=new Date().toISOString().slice(0,10);
  const access=await db.rpc('workforce_role',{p_owner:owner});const admin=['owner','hr'].includes(access.data??'');
  const [people,policies]=await Promise.all([db.from('employees').select('id,full_name,archived_at').eq('user_id',owner).order('full_name').limit(500),db.from('workforce_leave_policies').select('id,employee_id,leave_type,starts_on,ends_on,accrual_minutes,balance_cap_minutes,version,review_reference').eq('owner_id',owner).order('starts_on',{ascending:false}).limit(500)]);
  const selected=(policies.data??[]).find(p=>p.id===query.policy);
  const [balance,journal]=selected?await Promise.all([db.rpc('workforce_leave_balance',{p_policy:selected.id,p_as_of:today}),db.from('workforce_leave_ledger').select('id,effective_on,kind,minutes,reference,reason').eq('policy_id',selected.id).order('created_at',{ascending:false}).limit(50)]):[{data:null,error:null},{data:[],error:null}];
  const approved=selected?await db.from('workforce_requests').select('id,title,starts_on,ends_on,leave_type').eq('employee_id',selected.employee_id).eq('status','approved').eq('kind','leave').order('starts_on',{ascending:false}).limit(500):{data:[],error:null};
  const failed=access.error||people.error||policies.error||balance.error||journal.error||approved.error;
  const total=balance.data?.[0];
  const targets=(policies.data??[]).filter(p=>selected&&p.employee_id===selected.employee_id&&p.leave_type.trim().toLowerCase()===selected.leave_type.trim().toLowerCase()&&selected.ends_on&&p.starts_on>selected.ends_on&&p.starts_on<=today);
  const hidden=(operation:string)=><><input type="hidden" name="locale" value={locale}/><input type="hidden" name="owner" value={owner}/><input type="hidden" name="policy" value={selected?.id??''}/><input type="hidden" name="operation" value={operation}/></>;
  return <PlatformShell locale={locale} active="workforce"><div className="dashboard-content wf-ops"><PageHeading eyebrow={t('People operations','Operaciones de personal')} title={t('Leave policies and ledger','Políticas y registro de ausencias')} body={t('Reviewed policies and explicit manual postings. No automatic payroll or statutory entitlement.','Políticas revisadas y registros manuales explícitos. Sin nómina automática ni derechos legales calculados.')} action={<Link href={`/${locale}/dashboard/workforce/operations?owner=${owner}`}>{t('Command center','Centro de operaciones')}</Link>}/>
    {owner===user.id&&<p><Link href={`/${locale}/dashboard/workforce/leave/accrual`}>{t('Configure reviewed monthly automation','Configurar automatización mensual revisada')}</Link></p>}
    <p>{t('Monthly accrual stays manual unless the owner separately enables reviewed automation. Approved leave requests do not debit this ledger automatically. Carryover requires a reviewed transfer to a later policy; corrections require reviewed signed entries. Each employer must obtain appropriate HR/legal review. No policy or opening entry means unconfigured, not zero entitlement.','La acumulación mensual sigue siendo manual salvo que el propietario active por separado la automatización revisada. Las solicitudes aprobadas no descuentan este registro automáticamente. El arrastre requiere una transferencia revisada a una política posterior; las correcciones requieren registros revisados con signo. Cada empleador debe obtener revisión de RR. HH./legal. Sin política o saldo inicial significa sin configurar, no cero derechos.')}</p>
    {query.notice&&<p role={query.notice==='saved'?'status':'alert'}>{query.notice==='saved'?t('Saved.','Guardado.'):t('Not saved. Check permissions, dates, overlapping policies, opening balance, monthly limits and references. Refresh before retrying a stale policy change.','No guardado. Revisa permisos, fechas, superposición, saldo inicial, límites mensuales y referencias. Actualiza antes de reintentar un cambio obsoleto.')}</p>}
    {failed?<p role="alert">{t('Could not load complete balance data. No balance is shown.','No se pudieron cargar los datos completos. No se muestra saldo.')}</p>:<>
      <section className="panel"><h2>{t('Adopted policies','Políticas adoptadas')}</h2><ul>{(policies.data??[]).map(p=><li key={p.id}><Link href={`/${locale}/dashboard/workforce/leave?owner=${owner}&policy=${p.id}`}>{(people.data??[]).find(e=>e.id===p.employee_id)?.full_name??t('Employee','Empleado')} · {p.leave_type} · {p.starts_on} — {p.ends_on??t('Open-ended','Sin fecha final')}</Link></li>)}</ul>{!policies.data?.length&&<p>{t('No policies configured.','No hay políticas configuradas.')}</p>}</section>
      {selected&&<section className="panel"><h2>{selected.leave_type}</h2><p>{t('Posted balance as of','Saldo registrado al')} {today} (UTC): <strong>{total?.configured?`${formatLeaveMinutes(total.minutes,locale)} (${total.minutes} ${t('minutes','minutos')})`:t('Opening balance unconfigured','Saldo inicial sin configurar')}</strong></p><p>{t('Monthly accrual maximum in minutes','Máximo mensual de acumulación en minutos')}: {selected.accrual_minutes}. {t('Balance cap','Límite de saldo')}: {selected.balance_cap_minutes??t('Not capped','Sin límite')}.</p><p>{t('Amounts are shown in hours and minutes, not assumed working days. Entry fields still use minutes; a minus sign means a deduction.','Las cantidades se muestran en horas y minutos, no en días laborales supuestos. Los campos siguen usando minutos; el signo menos indica un descuento.')}</p><p>{t('Review reference','Referencia de revisión')}: {selected.review_reference}</p><h3>{t('Latest 50 postings; balance includes the full ledger','Últimos 50 registros; el saldo incluye el registro completo')}</h3><ul>{(journal.data??[]).map(e=><li key={e.id}>{e.effective_on} · {leaveEntryLabel(e.kind,locale)} · {formatLeaveMinutes(e.minutes,locale)} ({e.minutes} {t('minutes','minutos')}) · {e.reference} · {e.reason}</li>)}</ul>
        {admin&&<><details><summary>{t('Post reviewed entry','Registrar movimiento revisado')}</summary><p>{t('Use a unique source reference. Taken leave is negative; credits are positive. Start with one reviewed opening balance. One accrual entry per calendar month; no backdated postings. Correct errors with a signed adjustment referencing the original entry.','Usa una referencia única. Las ausencias usadas son negativas; los créditos positivos. Comienza con un saldo inicial revisado. Una acumulación por mes calendario; sin registros retroactivos. Corrige errores con un ajuste con signo que cite el registro original.')}</p><form action={leaveOperation}>{hidden('post')}<label>{t('Posting date','Fecha')}<input type="date" name="date" min={selected.starts_on} max={selected.ends_on&&selected.ends_on<today?selected.ends_on:today} required/></label><label>{t('Kind','Tipo')}<select name="kind">{['opening','accrual','taken','adjustment','carryover'].map(k=><option key={k} value={k}>{leaveEntryLabel(k,locale)}</option>)}</select></label><label>{t('Signed minutes (480 = 8 hours)','Minutos con signo (480 = 8 horas)')}<input type="number" name="minutes" min={-5256000} max={5256000} step={1} required/></label><label>{t('Unique source reference','Referencia única')}<input name="reference" maxLength={200} required/></label><label>{t('Review reason; no medical details','Motivo revisado; sin datos médicos')}<textarea name="reason" maxLength={1000} required/></label><button>{t('Post entry','Registrar')}</button></form></details><details><summary>{t('Shorten policy period','Acortar vigencia')}</summary><p>{t('This preserves history and cannot exclude posted entries. Adopt a new policy for later dates. Balances do not transfer automatically; review any opening balance separately.','Conserva el historial y no puede excluir registros existentes. Adopta una nueva política para fechas posteriores. Los saldos no se transfieren automáticamente; revisa el nuevo saldo inicial.')}</p><form action={leaveOperation}>{hidden('close')}<input type="hidden" name="version" value={selected.version}/><label>{t('Last effective day','Último día vigente')}<input type="date" name="end" min={selected.starts_on} max={selected.ends_on??'2200-12-31'} required/></label><label>{t('Reason','Motivo')}<textarea name="reason" maxLength={1000} required/></label><button>{t('Save end date','Guardar fecha final')}</button></form></details></>}
      </section>}
      {selected&&admin&&<section className="panel"><h2>{t('Post completed approved leave','Registrar ausencia aprobada y finalizada')}</h2><p>{t('This is an explicit reviewed action, not an automatic debit on approval. One policy must cover the whole request. The system checks every scheduled day and configured holiday against the minutes you review. Missing schedules or a different amount block posting. Repeating the same request does not debit twice. Use this flow instead of a separate manual debit for the same request. Requests spanning policies or requiring partial-day exceptions need a separately reviewed manual process.','Es una acción revisada explícita, no un descuento automático al aprobar. Una política debe cubrir toda la solicitud. El sistema verifica cada día y festivo configurado contra los minutos revisados. Horarios faltantes o cantidades distintas bloquean el registro. Repetir la misma solicitud no descuenta dos veces. Usa este proceso en vez de un descuento manual separado para la misma solicitud. Solicitudes entre políticas o con excepciones de días parciales requieren revisión manual separada.')}</p><form action={leaveOperation}>{hidden('approved_request')}<input type="hidden" name="version" value={selected.version}/><label>{t('Approved request','Solicitud aprobada')}<select name="request" required><option value="">{t('Choose completed leave','Elegir ausencia finalizada')}</option>{(approved.data??[]).filter(r=>r.leave_type?.trim().toLowerCase()===selected.leave_type.trim().toLowerCase()&&r.ends_on&&r.ends_on<=today).map(r=><option key={r.id} value={r.id}>{r.title} · {r.starts_on} — {r.ends_on}</option>)}</select></label><label>{t('Reviewed total scheduled minutes','Total revisado de minutos programados')}<input name="minutes" type="number" min={0} max={527040} step={1} required/></label><label>{t('Posting date (after leave; within policy dates)','Fecha de registro (después de la ausencia; dentro de la política)')}<input name="date" type="date" min={selected.starts_on} max={selected.ends_on&&selected.ends_on<today?selected.ends_on:today} required/></label><label>{t('Review reason; no medical details','Motivo revisado; sin datos médicos')}<textarea name="reason" maxLength={1000} required/></label><button>{t('Post verified debit','Registrar descuento verificado')}</button></form>{approved.data?.length===500&&<p>{t('Request list limited to 500 records.','Lista limitada a 500 registros.')}</p>}</section>}
      {selected&&admin&&total?.configured&&<section className="panel"><h2>{t('Transfer reviewed carryover','Transferir arrastre revisado')}</h2><p>{t('Transfer from this ended policy to a later policy for the same employee and leave type. The new policy must have no opening balance or postings. Both sides are recorded together. The transferred amount cannot exceed the source balance or target cap. Any remainder stays in this old ledger; nothing is automatically forfeited or paid out. This is a one-time reviewed operation, not a scheduled annual reset.','Transfiere de esta política finalizada a una posterior del mismo empleado y tipo. La nueva política no debe tener saldo inicial ni movimientos. Ambos lados se registran juntos. La cantidad no puede superar el saldo de origen ni el límite de destino. El remanente queda en este registro; nada se pierde ni se paga automáticamente. Es una operación revisada, no un reinicio anual programado.')}</p>{targets.length?<form action={leaveOperation}>{hidden('transfer')}<input name="version" type="hidden" value={selected.version}/><input name="expected_balance" type="hidden" value={total.minutes}/><label>{t('Target policy period','Período de política de destino')}<select name="target" required><option value="">{t('Choose the reviewed next period','Elegir el siguiente período revisado')}</option>{targets.map(p=><option key={p.id} value={`${p.id}:${p.version}`}>{p.starts_on} — {p.ends_on??t('Open-ended','Sin fecha final')} · {t('Cap','Límite')}: {p.balance_cap_minutes??t('Uncapped','Sin límite')}</option>)}</select></label><label>{t('Reviewed minutes to transfer','Minutos revisados para transferir')}<input type="number" name="minutes" min={0} max={Math.max(0,Math.min(5256000,Number(total.minutes)))} step={1} required/></label><label>{t('Policy review and reason (no medical details)','Revisión de política y motivo (sin datos médicos)')}<textarea name="reason" required maxLength={1000}/></label><label><input name="confirmed" type="checkbox" value="yes" required/>{t('I reviewed the source balance, target policy and carryover amount. Do not also enter a manual opening for this transfer.','Revisé el saldo de origen, la política de destino y la cantidad. No registrar también un saldo inicial manual para esta transferencia.')}</label><button>{t('Transfer and open new balance','Transferir y abrir nuevo saldo')}</button></form>:<p>{t('No later period is available in the loaded policies. Close this policy, adopt a later policy, and wait until its start date.','No hay período posterior disponible en las políticas cargadas. Cierra esta política, adopta una posterior y espera su fecha de inicio.')}</p>}</section>}
      {admin&&<section className="panel"><details><summary>{t('Adopt a reviewed policy','Adoptar política revisada')}</summary><form action={leaveOperation}>{hidden('adopt')}<label>{t('Employee','Empleado')}<select name="employee" required><option value="">{t('Choose','Elegir')}</option>{(people.data??[]).filter(e=>!e.archived_at).map(e=><option key={e.id} value={e.id}>{e.full_name}</option>)}</select></label><label>{t('Leave type','Tipo de ausencia')}<input name="type" maxLength={80} required/></label><label>{t('Effective from','Vigente desde')}<input type="date" name="start" min="1900-01-01" max="2200-12-31" required/></label><label>{t('Effective through','Vigente hasta')}<input type="date" name="end" min="1900-01-01" max="2200-12-31" required/></label><label>{t('Accrual method','Método de acumulación')}<select name="cadence" required defaultValue=""><option value="">{t('Choose supported method','Elegir método compatible')}</option><option value="manual_monthly">{t('Monthly, manually reviewed posting','Mensual, registro manual revisado')}</option></select></label><label>{t('Maximum monthly accrual minutes','Máximo mensual de minutos')}<input type="number" name="accrual" min={0} max={525600} step={1} required/></label><label>{t('Balance cap in minutes (blank = uncapped)','Límite de saldo en minutos (vacío = sin límite)')}<input type="number" name="cap" min={0} max={5256000} step={1}/></label><label>{t('Holiday treatment for planned leave','Tratamiento de festivos')}<select name="exclude" required defaultValue=""><option value="">{t('Choose','Elegir')}</option><option value="true">{t('Exclude listed holidays','Excluir festivos indicados')}</option><option value="false">{t('Include listed holidays','Incluir festivos indicados')}</option></select></label><label>{t('Holiday dates, one YYYY-MM-DD per line; blank explicitly means no listed holidays','Festivos, una fecha AAAA-MM-DD por línea; vacío significa sin festivos indicados')}<textarea name="holidays" maxLength={4026}/></label><label>{t('Reviewed policy reference (no confidential contents)','Referencia de política revisada (sin contenido confidencial)')}<input name="review" maxLength={1000} required/></label><label><input type="checkbox" name="confirmed" value="yes" required/>{t('I confirm these rules and the holiday list are reviewed and adopted for this employee. This is not a Crestview legal recommendation.','Confirmo que estas reglas y festivos están revisados y adoptados para este empleado. No es una recomendación legal de Crestview.')}</label><button>{t('Adopt policy','Adoptar política')}</button></form></details></section>}
      {(people.data?.length===500||policies.data?.length===500)&&<p role="status">{t('Display limit reached; policy list may be incomplete.','Límite alcanzado; la lista puede estar incompleta.')}</p>}
    </>}
  </div></PlatformShell>;
}
