import {WorkforceAccessNotice} from '@/components/workforce-access-notice';
import Link from 'next/link';
import {notFound,redirect} from 'next/navigation';
import {PlatformShell,PageHeading} from '@/components/platform-shell';
import {isLocale} from '@/lib/i18n';
import {createSupabaseServerClient} from '@/lib/supabase/server';
import PayrollImport from './import-form';
import {voidPayroll} from './actions';
import '../operations/workforce-operations.css';

type Total={currency:string;period_start:string;period_end:string;employees:number;gross_minor:number;employer_cost_minor:number;paid_hours_hundredths:number};
type Period=Total&{imports:number;cost_per_paid_hour:number|null;total_periods:number};
export default async function Payroll({params,searchParams}:{params:Promise<{locale:string}>;searchParams:Promise<{owner?:string;batch?:string;notice?:string}>}) {
  const {locale}=await params;if(!isLocale(locale))notFound();const t=(en:string,es:string)=>locale==='es'?es:en;
  const db=await createSupabaseServerClient();const {data:{user}}=await db.auth.getUser();if(!user)redirect(`/${locale}/sign-in`);
  const q=await searchParams,owner=q.owner||user.id;
  const access=await db.rpc('workforce_role',{p_owner:owner});
  if(access.error||!['owner','hr'].includes(access.data??''))return <PlatformShell locale={locale} active="workforce"><div className="dashboard-content"><h1>{t('Payroll analytics','Análisis de nómina')}</h1><p role="alert">{t('Owner or HR access is required.','Se requiere acceso de propietario o RR. HH.')}</p></div></PlatformShell>;
  const batches=await db.from('workforce_payroll_imports').select('id,reference,created_at,voided_at').eq('owner_id',owner).order('created_at',{ascending:false}).limit(50);
  const people=await db.from('employees').select('id,full_name').eq('user_id',owner).is('archived_at',null).order('full_name').limit(500);
  const periods=await db.rpc('workforce_payroll_periods',{p_owner:owner});
  const selected=q.batch?await db.from('workforce_payroll_imports').select('id,reference,created_at,voided_at').eq('owner_id',owner).eq('id',q.batch).maybeSingle():null;
  const totals=selected?.data?await db.rpc('workforce_payroll_totals',{p_import:selected.data.id}):null;
  const history=selected?.data?await db.from('workforce_payroll_history').select('id,action,reason,created_at').eq('import_id',selected.data.id).order('created_at'):null;
  const failed=batches.error||people.error||selected?.error||totals?.error||history?.error;
  const money=(n:number,c:string)=>new Intl.NumberFormat(locale,{style:'currency',currency:c,currencyDisplay:'code'}).format(Number(n)/100);
  return <PlatformShell locale={locale} active="workforce"><div className="dashboard-content wf-ops"><WorkforceAccessNotice owner={owner} locale={locale}/><PageHeading eyebrow={t('People operations','Operaciones de personal')} title={t('Payroll analytics','Análisis de nómina')} body={t('Reviewed source data for understanding labor costs. Payments and taxes remain with your external provider.','Datos revisados para entender costos laborales. Pagos e impuestos permanecen con tu proveedor externo.')} action={<Link href={`/${locale}/dashboard/workforce/operations?owner=${encodeURIComponent(owner)}`}>{t('Command center','Centro de operaciones')}</Link>}/>
    <p>{t('These are imported actuals, not a payroll calculation, forecast or live provider connection. Only owner/HR can view them. Overlapping periods for an employee are rejected to prevent double counting.','Son datos importados, no un cálculo de nómina, pronóstico ni conexión con un proveedor. Solo propietario/RR. HH. pueden consultarlos. Se rechazan períodos superpuestos por empleado para evitar duplicaciones.')}</p>
    {q.notice&&<p role={q.notice==='failed'?'alert':'status'}>{q.notice==='saved'?t('Import saved.','Importación guardada.'):q.notice==='voided'?t('Import voided. Source records and history are retained.','Importación anulada. Se conservan registros e historial.'):t('Change not saved. Check access and the correction reason.','Cambio no guardado. Revisa acceso y motivo de corrección.')}</p>}
    <section className="panel"><h2>{t('Labor cost by reporting period','Costo laboral por período')}</h2><p>{t('All active imports are included in each exact period and currency. Voided imports are excluded. Period length, employee coverage and source completeness can differ: these are not automatically like-for-like comparisons. Historical costs remain included after an employee is archived.','Se incluyen todas las importaciones activas de cada período exacto y moneda. Se excluyen las anuladas. La duración, cobertura de empleados e integridad de las fuentes pueden variar: no son comparaciones automáticamente equivalentes. Los costos históricos se conservan al archivar empleados.')}</p>
      {periods.error?<p role="alert">{t('Period analytics could not load. Do not treat missing totals as zero.','No se cargaron los totales por período. Los datos faltantes no equivalen a cero.')}</p>:<>
        {!periods.data?.length&&<p>{t('No active payroll source data yet.','Aún no hay datos de nómina activos.')}</p>}
        {Number(periods.data?.[0]?.total_periods)>100&&<p>{t('Showing the latest 100 period/currency groups of','Se muestran los últimos 100 grupos de período/moneda de')} {periods.data[0].total_periods}. {t('Each shown total still includes every matching import.','Cada total mostrado incluye todas las importaciones correspondientes.')}</p>}
        {((periods.data??[]) as Period[]).map(p=><details key={`${p.period_start}:${p.period_end}:${p.currency}`}><summary>{p.period_start} — {p.period_end} ({p.currency})</summary><dl>
          <div><dt>{t('Employees represented','Empleados representados')}</dt><dd>{p.employees}</dd></div><div><dt>{t('Source imports','Importaciones fuente')}</dt><dd>{p.imports}</dd></div>
          <div><dt>{t('Gross pay','Salario bruto')}</dt><dd>{Number.isSafeInteger(Number(p.gross_minor))?money(p.gross_minor,p.currency):t('Total exceeds display precision','El total supera la precisión de visualización')}</dd></div>
          <div><dt>{t('Total employer cost (includes gross)','Costo total del empleador (incluye bruto)')}</dt><dd>{Number.isSafeInteger(Number(p.employer_cost_minor))?money(p.employer_cost_minor,p.currency):t('Total exceeds display precision','El total supera la precisión de visualización')}</dd></div>
          <div><dt>{t('Source-reported paid hours','Horas pagadas según la fuente')}</dt><dd>{Number.isSafeInteger(Number(p.paid_hours_hundredths))?(Number(p.paid_hours_hundredths)/100).toFixed(2):'—'}</dd></div>
          <div><dt>{t('Employer cost per paid hour','Costo del empleador por hora pagada')}</dt><dd>{p.cost_per_paid_hour===null?t('Unavailable: zero paid hours','No disponible: cero horas pagadas'):new Intl.NumberFormat(locale,{style:'currency',currency:p.currency,currencyDisplay:'code'}).format(Number(p.cost_per_paid_hour))}</dd></div>
        </dl></details>)}<p>{t('Cost per paid hour is total employer cost divided by source-reported paid hours, not an employee wage or productivity score. No currency conversion or payment is performed.','El costo por hora pagada divide el costo total entre las horas pagadas de la fuente; no es un salario individual ni una medida de productividad. No se realizan conversiones de moneda ni pagos.')}</p>
      </>}
    </section>
    {failed?<p role="alert">{t('Payroll records could not load. Refresh before making changes.','No se pudieron cargar los registros. Actualiza antes de realizar cambios.')}</p>:<><details className="panel"><summary>{t('Employee IDs for your source mapping','Identificadores para mapear tu fuente')}</summary>{people.data?.map(e=><p key={e.id} style={{overflowWrap:'anywhere'}}>{e.full_name}: <code>{e.id}</code></p>)}{people.data?.length===500&&<p>{t('Showing the first 500 employees.','Se muestran los primeros 500 empleados.')}</p>}</details><PayrollImport locale={locale} owner={owner}/>
    <section className="panel"><h2>{t('Recent imports','Importaciones recientes')}</h2>{!batches.data?.length&&<p>{t('No payroll data imported. Labor costs are not yet available.','Sin datos importados. Los costos laborales aún no están disponibles.')}</p>}<ul>{batches.data?.map(b=><li key={b.id}><Link href={`/${locale}/dashboard/workforce/payroll?owner=${encodeURIComponent(owner)}&batch=${b.id}`}>{b.reference}</Link> — {b.created_at.slice(0,10)} {b.voided_at?t('(voided)','(anulada)'):''}</li>)}</ul>{batches.data?.length===50&&<p>{t('Showing the latest 50 imports.','Se muestran las últimas 50 importaciones.')}</p>}</section>
    {q.batch&&!selected?.data&&<p role="alert">{t('Selected import is unavailable.','Importación seleccionada no disponible.')}</p>}
    {selected?.data&&<section className="panel"><h2>{selected.data.reference}</h2><p>{t('Totals include all active rows in this import only. Separate periods and currencies are never combined.','Totales de todas las filas activas solo de esta importación. No se combinan períodos ni monedas diferentes.')}</p>{selected.data.voided_at&&<p>{t('Voided — excluded from totals.','Anulada — excluida de totales.')}</p>}
      {((totals?.data??[]) as Total[]).map(g=><section key={`${g.period_start}:${g.period_end}:${g.currency}`}><h3>{g.period_start} — {g.period_end} ({g.currency})</h3><dl><div><dt>{t('Employees in this period','Empleados en este período')}</dt><dd>{g.employees}</dd></div><div><dt>{t('Gross pay','Salario bruto')}</dt><dd>{money(g.gross_minor,g.currency)}</dd></div><div><dt>{t('Total employer cost (includes gross)','Costo total del empleador (incluye bruto)')}</dt><dd>{money(g.employer_cost_minor,g.currency)}</dd></div><div><dt>{t('Source-reported paid hours','Horas pagadas según la fuente')}</dt><dd>{(Number(g.paid_hours_hundredths)/100).toFixed(2)}</dd></div></dl></section>)}
      <h3>{t('Import history','Historial de importación')}</h3><ul>{history?.data?.map(h=><li key={h.id}>{h.created_at.slice(0,10)} — {h.action}: {h.reason}</li>)}</ul>
      {!selected.data.voided_at&&<details><summary>{t('Correct this import','Corregir esta importación')}</summary><p>{t('Void the entire batch first, then import the corrected full batch with a new reference. Voiding removes it from analytical totals immediately but preserves the original source.','Anula el lote completo y luego importa el lote corregido con otra referencia. La anulación lo excluye inmediatamente de los totales, pero conserva el origen.')}</p><form action={voidPayroll}><input type="hidden" name="locale" value={locale}/><input type="hidden" name="owner" value={owner}/><input type="hidden" name="batch" value={selected.data.id}/><label>{t('Correction reason','Motivo de corrección')}<textarea name="reason" required maxLength={1000}/></label><label><input type="checkbox" name="confirmed" value="yes" required/>{t('Void all rows in this import.','Anular todas las filas de esta importación.')}</label><button>{t('Void import','Anular importación')}</button></form></details>}
    </section>}</>}
  </div></PlatformShell>;
}
