import Link from 'next/link';
import {notFound,redirect} from 'next/navigation';
import {PlatformShell,PageHeading} from '@/components/platform-shell';
import {isLocale} from '@/lib/i18n';
import {createSupabaseServerClient} from '@/lib/supabase/server';
import PayrollImport from './import-form';
import {voidPayroll} from './actions';
import '../operations/workforce-operations.css';

type Total={currency:string;period_start:string;period_end:string;employees:number;gross_minor:number;employer_cost_minor:number;paid_hours_hundredths:number};
export default async function Payroll({params,searchParams}:{params:Promise<{locale:string}>;searchParams:Promise<{owner?:string;batch?:string;notice?:string}>}) {
  const {locale}=await params;if(!isLocale(locale))notFound();const t=(en:string,es:string)=>locale==='es'?es:en;
  const db=await createSupabaseServerClient();const {data:{user}}=await db.auth.getUser();if(!user)redirect(`/${locale}/sign-in`);
  const q=await searchParams,owner=q.owner||user.id;
  const access=await db.rpc('workforce_role',{p_owner:owner});
  if(access.error||!['owner','hr'].includes(access.data??''))return <PlatformShell locale={locale} active="workforce"><div className="dashboard-content"><h1>{t('Payroll analytics','Análisis de nómina')}</h1><p role="alert">{t('Owner or HR access is required.','Se requiere acceso de propietario o RR. HH.')}</p></div></PlatformShell>;
  const batches=await db.from('workforce_payroll_imports').select('id,reference,created_at,voided_at').eq('owner_id',owner).order('created_at',{ascending:false}).limit(50);
  const people=await db.from('employees').select('id,full_name').eq('user_id',owner).is('archived_at',null).order('full_name').limit(500);
  const selected=q.batch?await db.from('workforce_payroll_imports').select('id,reference,created_at,voided_at').eq('owner_id',owner).eq('id',q.batch).maybeSingle():null;
  const totals=selected?.data?await db.rpc('workforce_payroll_totals',{p_import:selected.data.id}):null;
  const history=selected?.data?await db.from('workforce_payroll_history').select('id,action,reason,created_at').eq('import_id',selected.data.id).order('created_at'):null;
  const failed=batches.error||people.error||selected?.error||totals?.error||history?.error;
  const money=(n:number,c:string)=>new Intl.NumberFormat(locale,{style:'currency',currency:c,currencyDisplay:'code'}).format(Number(n)/100);
  return <PlatformShell locale={locale} active="workforce"><div className="dashboard-content wf-ops"><PageHeading eyebrow={t('People operations','Operaciones de personal')} title={t('Payroll analytics','Análisis de nómina')} body={t('Reviewed source data for understanding labor costs. Payments and taxes remain with your external provider.','Datos revisados para entender costos laborales. Pagos e impuestos permanecen con tu proveedor externo.')} action={<Link href={`/${locale}/dashboard/workforce/operations?owner=${encodeURIComponent(owner)}`}>{t('Command center','Centro de operaciones')}</Link>}/>
    <p>{t('These are imported actuals, not a payroll calculation, forecast or live provider connection. Only owner/HR can view them. Overlapping periods for an employee are rejected to prevent double counting.','Son datos importados, no un cálculo de nómina, pronóstico ni conexión con un proveedor. Solo propietario/RR. HH. pueden consultarlos. Se rechazan períodos superpuestos por empleado para evitar duplicaciones.')}</p>
    {q.notice&&<p role={q.notice==='failed'?'alert':'status'}>{q.notice==='saved'?t('Import saved.','Importación guardada.'):q.notice==='voided'?t('Import voided. Source records and history are retained.','Importación anulada. Se conservan registros e historial.'):t('Change not saved. Check access and the correction reason.','Cambio no guardado. Revisa acceso y motivo de corrección.')}</p>}
    {failed?<p role="alert">{t('Payroll records could not load. Refresh before making changes.','No se pudieron cargar los registros. Actualiza antes de realizar cambios.')}</p>:<><details className="panel"><summary>{t('Employee IDs for your source mapping','Identificadores para mapear tu fuente')}</summary>{people.data?.map(e=><p key={e.id} style={{overflowWrap:'anywhere'}}>{e.full_name}: <code>{e.id}</code></p>)}{people.data?.length===500&&<p>{t('Showing the first 500 employees.','Se muestran los primeros 500 empleados.')}</p>}</details><PayrollImport locale={locale} owner={owner}/>
    <section className="panel"><h2>{t('Recent imports','Importaciones recientes')}</h2>{!batches.data?.length&&<p>{t('No payroll data imported. Labor costs are not yet available.','Sin datos importados. Los costos laborales aún no están disponibles.')}</p>}<ul>{batches.data?.map(b=><li key={b.id}><Link href={`/${locale}/dashboard/workforce/payroll?owner=${encodeURIComponent(owner)}&batch=${b.id}`}>{b.reference}</Link> — {b.created_at.slice(0,10)} {b.voided_at?t('(voided)','(anulada)'):''}</li>)}</ul>{batches.data?.length===50&&<p>{t('Showing the latest 50 imports.','Se muestran las últimas 50 importaciones.')}</p>}</section>
    {q.batch&&!selected?.data&&<p role="alert">{t('Selected import is unavailable.','Importación seleccionada no disponible.')}</p>}
    {selected?.data&&<section className="panel"><h2>{selected.data.reference}</h2><p>{t('Totals include all active rows in this import only. Separate periods and currencies are never combined.','Totales de todas las filas activas solo de esta importación. No se combinan períodos ni monedas diferentes.')}</p>{selected.data.voided_at&&<p>{t('Voided — excluded from totals.','Anulada — excluida de totales.')}</p>}
      {((totals?.data??[]) as Total[]).map(g=><section key={`${g.period_start}:${g.period_end}:${g.currency}`}><h3>{g.period_start} — {g.period_end} ({g.currency})</h3><dl><div><dt>{t('Employees in this period','Empleados en este período')}</dt><dd>{g.employees}</dd></div><div><dt>{t('Gross pay','Salario bruto')}</dt><dd>{money(g.gross_minor,g.currency)}</dd></div><div><dt>{t('Total employer cost (includes gross)','Costo total del empleador (incluye bruto)')}</dt><dd>{money(g.employer_cost_minor,g.currency)}</dd></div><div><dt>{t('Source-reported paid hours','Horas pagadas según la fuente')}</dt><dd>{(Number(g.paid_hours_hundredths)/100).toFixed(2)}</dd></div></dl></section>)}
      <h3>{t('Import history','Historial de importación')}</h3><ul>{history?.data?.map(h=><li key={h.id}>{h.created_at.slice(0,10)} — {h.action}: {h.reason}</li>)}</ul>
      {!selected.data.voided_at&&<details><summary>{t('Correct this import','Corregir esta importación')}</summary><p>{t('Void the entire batch first, then import the corrected full batch with a new reference. Voiding removes it from analytical totals immediately but preserves the original source.','Anula el lote completo y luego importa el lote corregido con otra referencia. La anulación lo excluye inmediatamente de los totales, pero conserva el origen.')}</p><form action={voidPayroll}><input type="hidden" name="locale" value={locale}/><input type="hidden" name="owner" value={owner}/><input type="hidden" name="batch" value={selected.data.id}/><label>{t('Correction reason','Motivo de corrección')}<textarea name="reason" required maxLength={1000}/></label><label><input type="checkbox" name="confirmed" value="yes" required/>{t('Void all rows in this import.','Anular todas las filas de esta importación.')}</label><button>{t('Void import','Anular importación')}</button></form></details>}
    </section>}</>}
  </div></PlatformShell>;
}
