import Link from "next/link";
import { notFound,redirect } from "next/navigation";
import { PlatformShell,PageHeading } from "@/components/platform-shell";
import { isLocale } from "@/lib/i18n";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { saveSchedule } from "./actions";
import "../operations/workforce-operations.css";

type Schedule={id:string;employee_id:string;starts_on:string;ends_on:string|null;timezone:string;daily_minutes:number[];version:number;cancelled:boolean;reason:string};
export default async function Schedules({params,searchParams}:{params:Promise<{locale:string}>;searchParams:Promise<{owner?:string;notice?:string}>}) {
  const {locale}=await params;if(!isLocale(locale))notFound();const t=(en:string,es:string)=>locale==="es"?es:en;
  const db=await createSupabaseServerClient();const {data:{user}}=await db.auth.getUser();if(!user)redirect(`/${locale}/sign-in`);
  const query=await searchParams;const owner=query.owner||user.id;
  const access=await db.rpc("workforce_role",{p_owner:owner});const admin=access.data==="owner"||access.data==="hr";
  const [people,data]=await Promise.all([db.from("employees").select("id,full_name,archived_at").eq("user_id",owner).order("full_name").limit(500),db.from("workforce_schedules").select("id,employee_id,starts_on,ends_on,timezone,daily_minutes,version,cancelled,reason").eq("owner_id",owner).order("starts_on",{ascending:false}).limit(500)]);
  const failed=access.error||people.error||data.error;const employees=people.data??[];const schedules=(data.data??[]) as Schedule[];
  const days=locale==="es"?["Lunes","Martes","Miércoles","Jueves","Viernes","Sábado","Domingo"]:["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];
  const form=(s?:Schedule)=><form action={saveSchedule}><input type="hidden" name="locale" value={locale}/><input type="hidden" name="owner" value={owner}/><input type="hidden" name="id" value={s?.id??""}/><input type="hidden" name="version" value={s?.version??0}/>{s?<input type="hidden" name="employee" value={s.employee_id}/>:<label>{t("Employee","Empleado")}<select name="employee" required><option value="">{t("Choose employee","Elegir empleado")}</option>{employees.filter(e=>!e.archived_at).map(e=><option key={e.id} value={e.id}>{e.full_name}</option>)}</select></label>}<label>{t("Effective from","Vigente desde")}<input type="date" name="start" defaultValue={s?.starts_on} min="1900-01-01" max="2200-12-31" required/></label><label>{t("Effective through (inclusive; optional)","Vigente hasta (inclusive; opcional)")}<input type="date" name="end" defaultValue={s?.ends_on??""} min="1900-01-01" max="2200-12-31"/></label><label>{t("IANA time zone","Zona horaria IANA")}<input name="timezone" defaultValue={s?.timezone??""} placeholder="America/Los_Angeles" required maxLength={100}/></label><fieldset><legend>{t("Planned minutes per day (480 = 8 hours; 0 = not scheduled)","Minutos previstos por día (480 = 8 horas; 0 = sin trabajo previsto)")}</legend>{days.map((day,i)=><label key={day}>{day}<input type="number" name={`day${i}`} defaultValue={s?.daily_minutes[i]} min={0} max={1440} step={1} required/></label>)}</fieldset><label>{t("Status","Estado")}<select name="cancelled" defaultValue={String(s?.cancelled??false)}><option value="false">{t("Effective for its dates","Vigente en sus fechas")}</option><option value="true">{t("Cancelled (retain history)","Cancelado (conservar historial)")}</option></select></label><label>{t("Reason for this change (no sensitive details)","Motivo del cambio (sin datos sensibles)")}<textarea name="reason" required maxLength={1000}/></label><button>{t("Save schedule","Guardar horario")}</button></form>;
  return <PlatformShell locale={locale} active="workforce"><div className="dashboard-content wf-ops"><PageHeading eyebrow={t("People operations","Operaciones de personal")} title={t("Work schedules","Horarios de trabajo")} body={t("Effective-dated weekly plans, scoped to the employees you may view.","Planes semanales con fechas de vigencia, limitados a los empleados que puedes consultar.")} action={<Link href={`/${locale}/dashboard/workforce/operations?owner=${owner}`}>{t("Command center","Centro de operaciones")}</Link>}/><p>{t("These are planned working minutes, not clock-in records, shift start times, payable hours or leave entitlements. Holidays and exceptions are not automatically deducted. No schedule means unconfigured, not zero hours. Owner/HR changes retain previous versions; overlapping effective periods are rejected.","Son minutos de trabajo previstos, no fichajes, horas de inicio, horas pagaderas ni derechos de ausencia. No se descuentan festivos ni excepciones automáticamente. Sin horario significa sin configurar, no cero horas. Los cambios de propietario/RR. HH. conservan versiones anteriores; se rechazan períodos superpuestos.")}</p>{query.notice&&<p role={query.notice==="saved"?"status":"alert"}>{query.notice==="saved"?t("Schedule saved.","Horario guardado."):t("Not saved. Check dates, all seven days, time zone, overlapping schedules and access. Refresh before retrying a stale edit.","No guardado. Revisa fechas, los siete días, zona horaria, superposición y acceso. Actualiza antes de reintentar un cambio obsoleto.")}</p>}{failed?<p role="alert">{t("Schedules could not load. Refresh before making changes.","No se pudieron cargar los horarios. Actualiza antes de hacer cambios.")}</p>:<>{admin&&<section className="panel"><details><summary>{t("Add employee schedule","Agregar horario de empleado")}</summary>{form()}</details></section>}{!schedules.length&&<p>{t("No schedules configured in the loaded records.","No hay horarios configurados en los registros cargados.")}</p>}{schedules.map(s=><section className="panel" key={s.id}><h2>{employees.find(e=>e.id===s.employee_id)?.full_name??t("Employee","Empleado")}</h2><p>{s.starts_on} — {s.ends_on??t("No end date","Sin fecha final")} · {s.timezone} · {s.cancelled?t("Cancelled","Cancelado"):t("Effective for its dates","Vigente en sus fechas")}</p><dl>{days.map((d,i)=><div key={d}><dt>{d}</dt><dd>{s.daily_minutes[i]} {t("minutes","minutos")}</dd></div>)}</dl><p>{t("Last change reason","Motivo del último cambio")}: {s.reason}</p>{admin&&!employees.find(e=>e.id===s.employee_id)?.archived_at&&<details><summary>{t("Edit schedule","Editar horario")}</summary>{form(s)}</details>}</section>)}{(employees.length>=500||schedules.length>=500)&&<p role="status">{t("Display limit reached; this may not be a complete list.","Límite de visualización alcanzado; la lista puede estar incompleta.")}</p>}</>}</div></PlatformShell>;
}
