'use client';
import {useRef,useState} from 'react';
import type {SignatureAppearance} from '@/lib/nda-signature';
export function NdaSignatureInput({value,onChange,disabled,es}:{value:SignatureAppearance;onChange:(value:SignatureAppearance)=>void;disabled:boolean;es:boolean}) {
 const uploadVersion=useRef(0),drawing=useRef(false),[error,setError]=useState('');
 const strokes=value.mode==='drawn'?value.strokes:[];
 return <fieldset disabled={disabled}><legend>{es?'Estilo de firma':'Signature style'}</legend>
  <label>{es?'Método':'Method'}<select aria-label={es?'Método':'Method'} value={value.mode} onChange={e=>{uploadVersion.current++;setError('');onChange(e.target.value==='drawn'?{mode:'drawn',strokes:[]}:e.target.value==='uploaded'?{mode:'uploaded',image:''}:{mode:'typed'});}}><option value="typed">{es?'Escribir':'Typed'}</option><option value="drawn">{es?'Dibujar':'Draw'}</option><option value="uploaded">{es?'Subir imagen':'Upload image'}</option></select></label>
  {value.mode==='drawn'&&<><p>{es?'Dibuja con el ratón o el dedo. También puedes usar una firma escrita.':'Draw with your mouse or finger. Typed signing remains available for keyboard use.'}</p><svg viewBox="0 0 600 180" role="img" aria-label={es?'Área para dibujar tu firma':'Draw your signature here'} style={{width:'100%',background:'#fff',border:'1px solid #809b8b',touchAction:'none'}} onPointerDown={e=>{if(disabled||strokes.length>=30)return;e.currentTarget.setPointerCapture(e.pointerId);drawing.current=true;const b=e.currentTarget.getBoundingClientRect();onChange({mode:'drawn',strokes:[...strokes,[[Math.max(0,Math.min(1,(e.clientX-b.x)/b.width)),Math.max(0,Math.min(1,(e.clientY-b.y)/b.height))]]]});}} onPointerMove={e=>{if(!drawing.current||disabled||!strokes.length||strokes.flat().length>=3000)return;const b=e.currentTarget.getBoundingClientRect(),last=strokes[strokes.length-1];if(last.length>=500)return;onChange({mode:'drawn',strokes:[...strokes.slice(0,-1),[...last,[Math.max(0,Math.min(1,(e.clientX-b.x)/b.width)),Math.max(0,Math.min(1,(e.clientY-b.y)/b.height))]]]});}} onPointerUp={()=>{drawing.current=false;}} onPointerCancel={()=>{drawing.current=false;}}>{strokes.map((s,i)=><polyline key={i} points={s.map(p=>`${p[0]*600},${p[1]*180}`).join(' ')} fill="none" stroke="#18392d" strokeWidth="3"/>)}</svg><button type="button" onClick={()=>onChange({mode:'drawn',strokes:[]})}>{es?'Borrar dibujo':'Clear drawing'}</button></>}
  {value.mode==='uploaded'&&<label>{es?'Imagen de tu firma (PNG o JPEG, máximo 160 KB)':'Your signature image (PNG or JPEG, max 160 KB)'}<input type="file" accept="image/png,image/jpeg" onChange={async e=>{const version=++uploadVersion.current,file=e.target.files?.[0];if(!file)return;setError('');if(file.size>160000||!['image/png','image/jpeg'].includes(file.type)){setError(es?'Usa PNG o JPEG de hasta 160 KB.':'Use PNG or JPEG up to 160 KB.');return;}const reader=new FileReader();reader.onload=()=>{if(version===uploadVersion.current)onChange({mode:'uploaded',image:String(reader.result)});};reader.onerror=()=>setError(es?'No se pudo leer la imagen.':'Could not read the image.');reader.readAsDataURL(file);}}/></label>}
  {error&&<p role="alert">{error}</p>}
 </fieldset>;
}
