import {test} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {PGlite} from '@electric-sql/pglite';
test('preparation stays private and account/funds verification cannot be self-assigned',async()=>{
 const db=new PGlite();const a='00000000-0000-4000-8000-000000000001',b='00000000-0000-4000-8000-000000000002';
 try{
 await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('test.uid',true),'')::uuid$$;create function auth.role() returns text language sql stable as $$select 'authenticated'::text$$;grant usage on schema auth to anon,authenticated;grant execute on all functions in schema auth to anon,authenticated;create table profiles(user_id uuid primary key,verification_status text default 'unverified',verification_note text);create table buyer_preferences(user_id uuid primary key,proof_of_funds_status text default 'not_provided');grant all on profiles,buyer_preferences to authenticated;create function timestamp_broker_profile() returns trigger language plpgsql as $$begin new.updated_at=now();return new;end;$$;`);
 await db.query('insert into auth.users values($1),($2)',[a,b]);await db.exec(await readFile(new URL('../supabase/migrations/0062_buyer_preparation.sql',import.meta.url),'utf8'));
 await db.query("select set_config('test.uid',$1,false)",[a]);await db.exec('set role authenticated');await db.query('insert into buyer_preparation(user_id)values($1)',[a]);
 await db.query('insert into profiles(user_id)values($1)',[a]);await db.query('insert into buyer_preferences(user_id)values($1)',[a]);
 await assert.rejects(db.exec("update profiles set verification_status='verified'"));await assert.rejects(db.exec("update profiles set verification_note='Self approved'"));await assert.rejects(db.exec("update buyer_preferences set proof_of_funds_status='verified'"));await db.exec("update buyer_preferences set proof_of_funds_status='available'");
 await db.exec("update buyer_preparation set path='searching',completed_steps=array['goals']");await assert.rejects(db.exec("update buyer_preparation set completed_steps=array['approved']"));
 await db.exec('reset role');await db.query("select set_config('test.uid',$1,false)",[b]);await db.exec('set role authenticated');assert.equal((await db.query('select * from buyer_preparation')).rows.length,0);assert.equal((await db.query("update buyer_preparation set path='preparing' returning user_id")).rows.length,0);await assert.rejects(db.query('insert into buyer_preparation(user_id)values($1)',[a]));
 await db.exec('reset role;set role anon');await assert.rejects(db.exec('select * from buyer_preparation'));
 }finally{await db.close();}
});
