import {z} from 'zod';
export const preparationSteps=[
 {id:'goals',en:'Define the business and location you want',es:'Define el negocio y la ubicación que buscas',detail:'Start with your interests, transferable skills and preferred location. You can change your mind as you learn.',detailEs:'Empieza con tus intereses, habilidades transferibles y ubicación preferida. Puedes cambiar de opinión mientras aprendes.',href:'/dashboard/settings#listing-alerts'},
 {id:'role',en:'Understand your role as an owner',es:'Comprende tu papel como propietario',detail:'Consider whether you want to operate the business day to day. Ask how much the current owner does and what experience or licenses the business requires.',detailEs:'Considera si quieres operar el negocio a diario. Pregunta qué hace el propietario actual y qué experiencia o licencias requiere el negocio.',href:'/guides'},
 {id:'budget',en:'Draft an initial acquisition budget',es:'Prepara un presupuesto inicial',detail:'A starting estimate is enough. You do not need funds today to use this preparation plan. Record what you know and what you still need to explore.',detailEs:'Basta con una estimación inicial. No necesitas fondos hoy para usar este plan. Anota lo que sabes y lo que necesitas explorar.',href:'/dashboard/settings#listing-alerts'},
 {id:'reserves',en:'Consider costs beyond the purchase price',es:'Considera costos adicionales al precio',detail:'Include working capital, professional fees, transition costs and personal reserves. Calculator results are scenarios, not a recommendation or approval.',detailEs:'Incluye capital de trabajo, honorarios, transición y reservas personales. Los cálculos son escenarios, no recomendaciones ni aprobaciones.',href:'/guides/tools'},
 {id:'financing',en:'Prepare questions about financing',es:'Prepara preguntas sobre financiación',detail:'List potential funding sources and questions for a lender. Exploring financing is a valid stage; no approval is required to complete this learning step.',detailEs:'Enumera fuentes posibles y preguntas para un prestamista. Explorar financiación es una etapa válida; no necesitas aprobación para completar este paso educativo.',href:'/guides'},
 {id:'advisors',en:'Identify the professional help you may need',es:'Identifica el apoyo profesional que necesitas',detail:'Consider accounting, legal, lending and industry advice. Identifying whom you may need is enough here; you do not need to hire everyone now.',detailEs:'Considera apoyo contable, legal, financiero y del sector. Basta con identificarlo; no necesitas contratar a todos ahora.',href:'/guides'},
 {id:'financials',en:'Learn the basic financial terms',es:'Aprende los conceptos financieros básicos',detail:'Understand the difference between revenue, profit and cash flow. Write down questions rather than assuming the listing tells the whole story.',detailEs:'Comprende la diferencia entre ingresos, beneficios y flujo de caja. Anota preguntas en lugar de asumir que el anuncio cuenta toda la historia.',href:'/guides'},
 {id:'confidentiality',en:'Understand confidentiality and next steps',es:'Comprende la confidencialidad y los próximos pasos',detail:'Review NDA obligations before signing. Completing this plan does not grant access to confidential documents or qualify you for every business.',detailEs:'Revisa las obligaciones del NDA antes de firmar. Completar este plan no concede documentos confidenciales ni te califica para todos los negocios.',href:'/how-it-works'},
] as const;
export const preparationSchema=z.object({path:z.enum(['preparing','searching']),completed_steps:z.array(z.enum(['goals','role','budget','reserves','financing','advisors','financials','confidentiality'])).max(8).transform(v=>[...new Set(v)])});
