export type Opportunity = {
  id: string;
  title: string;
  publicBusinessName: string | null;
  location: string;
  industry: string;
  price: string;
  priceValue: number | null;
  revenue: string;
  revenueValue: number | null;
  cashFlow: string;
  cashFlowValue: number | null;
  ebitda: string;
  ebitdaValue: number | null;
  status: string;
  source: string;
  sourceUrl: string;
  sourceId: string;
  lastChecked: string;
  brokerName?: string;
  brokerEmail?: string;
  brokerPhone?: string;
  description: string;
  highlights: string[];
  missing: string[];
};

const featuredOpportunities: Opportunity[] = [
  {
    id: "precision-heat-air",
    title: "Precision Heat & Air",
    publicBusinessName: "Precision Heat & Air",
    location: "Palm Springs, CA",
    industry: "HVAC",
    price: "$229,000",
    priceValue: 229000,
    revenue: "$637,000",
    revenueValue: 637000,
    cashFlow: "$57,000",
    cashFlowValue: 57000,
    ebitda: "N/A",
    ebitdaValue: null,
    status: "Active when checked",
    source: "BizBuySell",
    sourceUrl: "https://www.bizbuysell.com/business-opportunity/precision-heat-and-air/2520326/",
    sourceId: "2520326",
    lastChecked: "July 25, 2026",
    description: "Full-service heating and air conditioning company serving residential and commercial customers in the Coachella Valley.",
    highlights: ["Established in 1995", "Public business name disclosed", "Residential and commercial service"],
    missing: ["EBITDA", "Customer concentration", "Owner hours", "Financing terms"],
  },
  {
    id: "hvac-duct-insulation-alameda",
    title: "Profitable HVAC, Duct & Insulation Company",
    publicBusinessName: null,
    location: "Alameda County, CA",
    industry: "HVAC and insulation",
    price: "$1,000,000",
    priceValue: 1000000,
    revenue: "$3,000,000",
    revenueValue: 3000000,
    cashFlow: "$350,000",
    cashFlowValue: 350000,
    ebitda: "N/A",
    ebitdaValue: null,
    status: "Active when checked",
    source: "BizBuySell",
    sourceUrl: "https://www.bizbuysell.com/business-opportunity/profitable-hvac-duct-and-insulation-company/2455598/",
    sourceId: "2455598",
    lastChecked: "July 25, 2026",
    description: "Bay Area HVAC, ducting, insulation, and energy-efficiency company described as operating since 2015.",
    highlights: ["Seller reports 500+ five-star reviews", "Repeat and referral customer base", "Relocatable listing"],
    missing: ["EBITDA", "Customer concentration", "Tax-return verification", "Owner dependency"],
  },
  {
    id: "turnkey-hvac-real-estate",
    title: "Profitable Turnkey HVAC Business with Real Estate",
    publicBusinessName: null,
    location: "Tuolumne County, CA",
    industry: "HVAC",
    price: "$2,000,000",
    priceValue: 2000000,
    revenue: "$2,192,000",
    revenueValue: 2192000,
    cashFlow: "Inquire with seller",
    cashFlowValue: null,
    ebitda: "$400,000",
    ebitdaValue: 400000,
    status: "Active when checked",
    source: "BizBuySell",
    sourceUrl: "https://www.bizbuysell.com/business-opportunity/profitable-turnkey-hvac-business-with-real-estate-for-sale/2407884/",
    sourceId: "2407884",
    lastChecked: "July 25, 2026",
    description: "HVAC business established in 2003 with commercial real estate, vehicles, inventory, tools, and equipment included in the listing.",
    highlights: ["Real estate listed at $450,000", "200+ reported service contracts", "Residential and commercial work"],
    missing: ["SDE or cash flow", "Asset allocation", "Lease or property diligence", "Customer concentration"],
  },
  {
    id: "norcal-ventilation-controls",
    title: "Northern Californian Ventilation Controls Company, Absentee Owned",
    publicBusinessName: null,
    location: "Northern California",
    industry: "Ventilation controls",
    price: "$75,000",
    priceValue: 75000,
    revenue: "Inquire with broker",
    revenueValue: null,
    cashFlow: "Inquire with broker",
    cashFlowValue: null,
    ebitda: "N/A",
    ebitdaValue: null,
    status: "Active when checked",
    source: "Sunbelt Network",
    sourceUrl: "https://www.sunbeltnetwork.com/business-search/business-results/ss-hvac-businesses-in-california-25/",
    sourceId: "SC2269",
    lastChecked: "July 25, 2026",
    description: "Northern California ventilation controls company described by the broker as approximately 15 years old and absentee owned.",
    highlights: ["Local broker listing", "Absentee-owned description", "Low disclosed asking price"],
    missing: ["Revenue", "Cash flow", "EBITDA", "Customer mix", "Reason for sale"],
  },
  {
    id: "commercial-residential-hvac-intermountain",
    title: "Commercial & Residential HVAC Company",
    publicBusinessName: null,
    location: "Intermountain West",
    industry: "HVAC",
    price: "$4,900,000",
    priceValue: 4900000,
    revenue: "$8,811,024",
    revenueValue: 8811024,
    cashFlow: "$1,379,650",
    cashFlowValue: 1379650,
    ebitda: "N/A",
    ebitdaValue: null,
    status: "Active when checked",
    source: "Murphy Business",
    sourceUrl: "https://murphybusiness.com/logan/business-brokerage/details/22075/commercial-and-residential-hvac-company",
    sourceId: "18924",
    lastChecked: "July 25, 2026",
    description: "Two-brand HVAC operation serving commercial, institutional, and residential customers in the Intermountain West.",
    highlights: ["Local broker listing", "Commercial and residential divisions", "Disclosed SDE"],
    missing: ["EBITDA", "Exact location", "Customer concentration", "Debt and working-capital needs"],
  },
  {
    id: "engineering-services-high-margin",
    title: "69% EBITDA Margin Engineering Services Firm with High-End Clientele",
    publicBusinessName: null,
    location: "California",
    industry: "Engineering services",
    price: "$24,372,532",
    priceValue: 24372532,
    revenue: "Inquire with broker",
    revenueValue: null,
    cashFlow: "$4,896,792",
    cashFlowValue: 4896792,
    ebitda: "Inquire with broker",
    ebitdaValue: null,
    status: "Active when checked",
    source: "Transworld Business Advisors",
    sourceUrl: "https://www.tworld.com/locations/california/irvinelongbeach/business-listing-search",
    sourceId: "Broker page listing",
    lastChecked: "July 25, 2026",
    brokerName: "Transworld Business Advisors of Orange",
    brokerPhone: "(714) 923-1222",
    description: "California engineering-services opportunity advertised by Transworld with high-end clientele and a seller-disclosed earnings figure.",
    highlights: ["Independent broker source", "High disclosed earnings", "California location"],
    missing: ["Revenue", "Exact location", "Client concentration", "Normalized EBITDA support"],
  },
  {
    id: "child-behavior-therapy",
    title: "Mostly Absentee Child Behavior and Therapy Business for Sale",
    publicBusinessName: null,
    location: "Orange County, CA",
    industry: "Behavioral health",
    price: "$1,440,000",
    priceValue: 1440000,
    revenue: "Inquire with broker",
    revenueValue: null,
    cashFlow: "$461,635",
    cashFlowValue: 461635,
    ebitda: "N/A",
    ebitdaValue: null,
    status: "Active when checked",
    source: "Transworld Business Advisors",
    sourceUrl: "https://www.tworld.com/locations/california/irvinelongbeach/business-listing-search",
    sourceId: "Broker page listing",
    lastChecked: "July 25, 2026",
    brokerName: "Transworld Business Advisors of Orange",
    brokerPhone: "(714) 923-1222",
    description: "Orange County child behavior and therapy business advertised as mostly absentee-run.",
    highlights: ["Independent broker source", "Absentee-run description", "Disclosed seller earnings"],
    missing: ["Revenue", "Payer concentration", "Licensing and credentialing", "Clinician retention"],
  },
  {
    id: "family-medical-practice",
    title: "Amazing Family Medical Practice with 43.5% EBITDA Margins",
    publicBusinessName: null,
    location: "Orange County, CA",
    industry: "Medical practice",
    price: "$3,000,000",
    priceValue: 3000000,
    revenue: "Inquire with broker",
    revenueValue: null,
    cashFlow: "$1,236,709",
    cashFlowValue: 1236709,
    ebitda: "Inquire with broker",
    ebitdaValue: null,
    status: "Active when checked",
    source: "Transworld Business Advisors",
    sourceUrl: "https://www.tworld.com/locations/california/irvinelongbeach/business-listing-search",
    sourceId: "Broker page listing",
    lastChecked: "July 25, 2026",
    brokerName: "Transworld Business Advisors of Orange",
    brokerPhone: "(714) 923-1222",
    description: "Orange County family medical practice marketed with a seller-reported EBITDA margin.",
    highlights: ["Independent broker source", "Healthcare opportunity", "Disclosed seller earnings"],
    missing: ["Revenue", "Provider dependency", "Payer mix", "Compliance and licensing review"],
  },
];

const money = (value: number | null, unknownLabel = "Inquire with broker") =>
  value === null ? unknownLabel : `$${value.toLocaleString("en-US")}`;

const businessTeamListings: Opportunity[] = ([
  ["litigation-analytics-platform", "High-Margin Litigation Analytics Platform", "Legal technology", "California", 3500000, 1200000, 892849, "11823"],
  ["general-engineering-company", "Profitable General Engineering Company", "Engineering and construction", "California", null, 3526764, 766666, "IR11227"],
  ["pipe-lining-coating", "Market-Leading Pipe Lining and Coating Company", "Industrial services", "California", null, 5262975, 618412, "FR11699"],
  ["bay-area-catering", "Profitable Full-Service Bay Area Catering Business", "Food service and catering", "Bay Area, CA", 1600000, 2882885, 419850, "11757"],
  ["manufactured-home-brokerage", "Manufactured Home Brokerage", "Real estate services", "California", 625000, 7474300, 325948, "SE11874"],
  ["mediterranean-market", "Mediterranean Market, Deli, Bakery and Halal Food", "Grocery and food service", "California", 1275000, 2228221, 315529, "11762"],
  ["sacramento-landscape-installation", "Sacramento Landscape Installation Business", "Landscaping", "Sacramento, CA", 550000, 1899278, 294033, "SA11794"],
  ["glass-glazing-business", "Very Profitable Glass and Glazing Business", "Glass and construction", "California", 300000, 455973, 287580, "SA11701"],
  ["transmission-business", "Transmission Business with Positive SDE, Semi-Absentee", "Automotive service", "Northern California", 749000, 771629, 278922, "SA11703"],
  ["artisan-pizza", "Absentee-Run Quick-Service Artisan Pizza Business", "Restaurant", "California", 700000, 1021449, 268392, "ST11822"],
  ["san-jose-physical-therapy", "Profitable Physical Therapy Practice in San Jose", "Physical therapy", "San Jose, CA", 1100000, 1011283, 263694, "11680"],
  ["radiant-heating-contractor", "High-Margin Radiant Heating Contractor", "Specialty contracting", "Los Angeles, CA", 599000, 1001596, 257619, "SF11754"],
  ["indian-grocery-market", "Highly Profitable Indian Grocery Market", "Grocery", "California", 450000, 651562, 250670, "SF11841"],
  ["bicycle-shop", "Beloved Bicycle Shop with Growth Potential", "Bicycle retail and service", "California", 365000, 1089899, 128783, "11902"],
  ["window-coverings", "Profitable Window Covering Business in South Bay", "Home services and retail", "South Bay, CA", 200000, 485554, 123263, "11597"],
  ["structural-engineering", "Structural Engineering Business", "Engineering services", "California", 300000, 780791, 121742, "SF11515"],
  ["business-connectivity", "Business Connectivity Services Company", "Telecommunications services", "California", 995000, 1103898, 121305, "SF11728"],
  ["natural-foods-norcal", "Natural Foods Business Known Locally in Northern California", "Natural foods", "Northern California", 270000, 545299, 119255, "SA11721"],
  ["bay-area-design-build", "Award-Winning Bay Area Design-Build Firm", "Design and construction", "Bay Area, CA", 4000000, 4176960, 119040, "11316"],
  ["hvac-home-based", "Home-Based HVAC Business", "HVAC", "Northern California", 215000, 324452, 105622, "SA11896"],
] satisfies Array<[string, string, string, string, number | null, number | null, number | null, string]>).map(
  ([id, title, industry, location, price, revenue, cashFlow, sourceId]): Opportunity => ({
    id,
    title,
    publicBusinessName: null,
    location,
    industry,
    price: money(price),
    priceValue: price,
    revenue: money(revenue),
    revenueValue: revenue,
    cashFlow: money(cashFlow),
    cashFlowValue: cashFlow,
    ebitda: "N/A",
    ebitdaValue: null,
    status: "Active when checked",
    source: "Business Team",
    sourceUrl: "https://www.business-team.com/buy-a-business/search-results.aspx?lid=ca",
    sourceId,
    lastChecked: "July 25, 2026",
    brokerName: "Business Team",
    description: `${title} listed through Business Team. The public search result reports the figures shown here; additional operating and transaction details require broker inquiry.`,
    highlights: ["Independent broker listing", `${industry} opportunity`, "Public revenue and adjusted-earnings figures shown when available"],
    missing: ["EBITDA", "Exact business name", "Customer concentration", "Owner involvement", "Supporting financial records"],
  }),
);

const additionalBrokerListings: Opportunity[] = [
  {
    id: "awards-apparel-signage",
    title: "Established Awards, Promotional Products, Custom Apparel and Signage",
    publicBusinessName: null,
    location: "Southern California",
    industry: "Printing, apparel and signage",
    price: "$690,000",
    priceValue: 690000,
    revenue: "$1,287,829",
    revenueValue: 1287829,
    cashFlow: "$276,153",
    cashFlowValue: 276153,
    ebitda: "N/A",
    ebitdaValue: null,
    status: "Active when checked",
    source: "BizBen / TLG Business Broker",
    sourceUrl: "https://www.bizben.com/business-for-sale/established-awards-promo-products-custom-apparel-signage-7156398",
    sourceId: "7156398",
    lastChecked: "July 25, 2026",
    brokerName: "Ian Lashley",
    brokerEmail: "ian@tlgbusinessbroker.com",
    brokerPhone: "(805) 535-3693",
    description: "Long-established awards, recognition, custom apparel, signage, and promotional-products company serving Southern California.",
    highlights: ["SBA prequalified according to listing", "More than 50 years in operation", "Seller reports repeat institutional customers"],
    missing: ["EBITDA", "Customer concentration schedule", "Normalized owner compensation", "Current lease confirmation"],
  },
  {
    id: "health-insurance-book",
    title: "Group Health Insurance Agency and Book of Business",
    publicBusinessName: null,
    location: "Banning, Riverside County, CA",
    industry: "Insurance agency",
    price: "$390,000",
    priceValue: 390000,
    revenue: "$130,804",
    revenueValue: 130804,
    cashFlow: "$124,247",
    cashFlowValue: 124247,
    ebitda: "N/A",
    ebitdaValue: null,
    status: "Active when checked",
    source: "BizBen / First Choice Business Brokers",
    sourceUrl: "https://www.bizben.com/business-for-sale/life-health-insurance-agency-6849908",
    sourceId: "6849908",
    lastChecked: "July 25, 2026",
    brokerName: "Sarkis Kaladzhyan",
    brokerEmail: "sarkisk@fcbb.com",
    brokerPhone: "(818) 634-7778",
    description: "Owner-operated health-insurance agency established in 1989 with a book concentrated in group medical policies.",
    highlights: ["Seller financing indicated", "Seller reports established carrier relationships", "Transition support described"],
    missing: ["EBITDA", "Policy retention history", "Commission statements", "License-transfer plan"],
  },
];

export const opportunities: Opportunity[] = [
  ...featuredOpportunities,
  ...businessTeamListings,
  ...additionalBrokerListings,
];

export const pipelineColumns = [
  { title: "Saved", count: 5, deals: ["Precision Heat & Air", "Northern Californian Ventilation Controls"] },
  { title: "Screening", count: 3, deals: ["Profitable HVAC, Duct & Insulation Company"] },
  { title: "Evaluating", count: 2, deals: ["Commercial & Residential HVAC Company"] },
  { title: "Due diligence", count: 1, deals: ["Turnkey HVAC Business with Real Estate"] },
];

export const platformTasks = [
  { title: "Request customer concentration report", deal: "HVAC, Duct & Insulation Company", due: "Today", status: "Open" },
  { title: "Request three years of tax returns", deal: "Turnkey HVAC Business", due: "Tomorrow", status: "Open" },
  { title: "Confirm broker listing status", deal: "Precision Heat & Air", due: "Jul 29", status: "Open" },
  { title: "Review licensing transfer requirements", deal: "Commercial & Residential HVAC", due: "Aug 1", status: "Open" },
];

export function getOpportunity(id: string) {
  return opportunities.find((item) => item.id === id);
}
