import type { Locale } from "@/lib/i18n";

const copy = {
  en: {
    common: {
      browse: "Browse opportunities",
      viewAll: "View all",
      noDueDate: "No due date",
      general: "General",
      saved: "Saved",
      screening: "Screening",
      evaluating: "Evaluating",
      diligence: "Due diligence",
      negotiation: "Negotiation",
      closing: "Closing",
      complete: "Complete",
      passed: "Passed",
    },
    overview: {
      eyebrow: "Your workspace",
      title: "Your acquisition overview",
      body: "Live activity from your saved deals, tasks, and diligence work.",
      saved: "Saved opportunities",
      active: "Active deals",
      diligence: "Diligence items",
      due: "Open tasks",
      attention: "Need attention",
      priority: "Recently updated deals",
      actions: "Next actions",
      emptyDeals: "No saved opportunities yet.",
      emptyTasks: "No open tasks. Your work queue is clear.",
    },
    opportunities: {
      eyebrow: "DealFlow",
      title: "Businesses for sale",
      body: "Search sourced public listings. Confidential businesses keep their broker-provided titles.",
      seller: "Seller-reported information",
      notice: "Listings may change or be withdrawn. N/A and “Inquire with seller” mean the value was not publicly disclosed, never zero.",
      compare: "Compare selected",
      lists: "Saved lists",
    },
    pipeline: {
      eyebrow: "Deal management",
      title: "Acquisition pipeline",
      body: "Your saved opportunities, current stages, and next actions are stored securely with your account.",
      ready: "Your pipeline is ready",
      empty: "Save an opportunity or select “Begin acquisition” to add your first real deal.",
      next: "Choose the next action for this deal.",
      update: "Update",
    },
    tasks: {
      eyebrow: "Work queue",
      title: "Tasks",
      body: "Create tasks, connect them to opportunities, and track due dates and priority.",
      task: "Task",
      opportunity: "Opportunity",
      due: "Due date",
      priority: "Priority",
      add: "Add task",
      empty: "No tasks yet",
      emptyBody: "Create the first task above. It will be stored with your account.",
    },
  },
  es: {
    common: {
      browse: "Explorar oportunidades",
      viewAll: "Ver todo",
      noDueDate: "Sin fecha límite",
      general: "General",
      saved: "Guardado",
      screening: "Evaluación inicial",
      evaluating: "Evaluando",
      diligence: "Debida diligencia",
      negotiation: "Negociación",
      closing: "Cierre",
      complete: "Completado",
      passed: "Descartado",
    },
    overview: {
      eyebrow: "Tu espacio de trabajo",
      title: "Resumen de tus adquisiciones",
      body: "Actividad en vivo de tus negocios guardados, tareas y diligencia.",
      saved: "Oportunidades guardadas",
      active: "Negocios activos",
      diligence: "Elementos de diligencia",
      due: "Tareas abiertas",
      attention: "Necesitan atención",
      priority: "Negocios actualizados recientemente",
      actions: "Próximas acciones",
      emptyDeals: "Aún no hay oportunidades guardadas.",
      emptyTasks: "No hay tareas abiertas. Tu lista está al día.",
    },
    opportunities: {
      eyebrow: "DealFlow",
      title: "Negocios en venta",
      body: "Busca anuncios públicos con fuente. Los negocios confidenciales conservan el título del corredor.",
      seller: "Información proporcionada por el vendedor",
      notice: "Los anuncios pueden cambiar o retirarse. N/A y “Consultar con el vendedor” significan que el valor no fue publicado, nunca cero.",
      compare: "Comparar seleccionados",
      lists: "Listas guardadas",
    },
    pipeline: {
      eyebrow: "Gestión de negocios",
      title: "Proceso de adquisición",
      body: "Tus oportunidades, etapas y próximos pasos se guardan de forma segura con tu cuenta.",
      ready: "Tu proceso está listo",
      empty: "Guarda una oportunidad o selecciona “Iniciar adquisición” para agregar tu primer negocio.",
      next: "Elige la próxima acción para este negocio.",
      update: "Actualizar",
    },
    tasks: {
      eyebrow: "Lista de trabajo",
      title: "Tareas",
      body: "Crea tareas, relaciónalas con oportunidades y controla fechas y prioridades.",
      task: "Tarea",
      opportunity: "Oportunidad",
      due: "Fecha límite",
      priority: "Prioridad",
      add: "Agregar tarea",
      empty: "Aún no hay tareas",
      emptyBody: "Crea la primera tarea arriba. Se guardará con tu cuenta.",
    },
  },
} as const;

export function platformCopy(locale: Locale) {
  return copy[locale];
}
