import { z } from "zod";
export const sellerPreparationSteps = [
  { id: "authority", en: "Confirm authority and seller approval", es: "Confirmar autorización del vendedor", detail: "Confirm what you are authorized to market and disclose, including the seller’s confidentiality instructions.", detailEs: "Confirma qué puedes anunciar y divulgar, incluidas las instrucciones de confidencialidad del vendedor." },
  { id: "periods", en: "Identify the financial periods", es: "Identificar los períodos financieros", detail: "Label each statement’s start and end dates, whether it is full-year or year-to-date, and whether figures are actual or projected.", detailEs: "Indica fechas, si cubre el año completo o un período parcial, y si las cifras son reales o proyectadas." },
  { id: "reconciliation", en: "Explain differences between advertised and reported figures", es: "Explicar diferencias entre cifras anunciadas y declaradas", detail: "Prepare a clear explanation and supporting records for differences in revenue, earnings or asking-price assumptions. Do not treat estimates as verified results.", detailEs: "Prepara explicaciones y respaldo para diferencias de ingresos, beneficios o supuestos del precio. No presentes estimaciones como resultados verificados." },
  { id: "adjustments", en: "Document owner compensation and add-backs", es: "Documentar remuneración del propietario y ajustes", detail: "Separate reported figures from proposed adjustments and record the explanation and evidence for each adjustment.", detailEs: "Separa las cifras declaradas de los ajustes propuestos y registra la explicación y evidencia de cada ajuste." },
  { id: "assets", en: "Clarify what is included and excluded", es: "Aclarar qué se incluye y excluye", detail: "Describe inventory, equipment, working capital, property and liabilities without implying that everything transfers automatically.", detailEs: "Describe inventario, equipos, capital de trabajo, inmuebles y obligaciones sin implicar una transferencia automática." },
  { id: "transfer", en: "Identify transfer and transition questions", es: "Identificar preguntas de transferencia y transición", detail: "List leases, customer contracts, licenses, staffing and owner responsibilities that need review with the appropriate professionals.", detailEs: "Enumera arrendamientos, contratos, licencias, personal y funciones del propietario que deben revisarse con profesionales." },
  { id: "confidentiality", en: "Review the NDA and sharing plan", es: "Revisar el NDA y el plan de acceso", detail: "Use the reviewed agreement and decide which documents may be shared at each stage. This checklist does not release any document.", detailEs: "Usa el acuerdo revisado y decide qué documentos compartir en cada etapa. Esta lista no libera documentos." },
  { id: "questions", en: "Prepare answers and record unresolved questions", es: "Preparar respuestas y registrar preguntas pendientes", detail: "Keep unanswered items visible. An incomplete item is a follow-up task, not a reason to invent an answer or promise a result.", detailEs: "Mantén visibles los pendientes. Un elemento incompleto requiere seguimiento, no inventar respuestas ni prometer resultados." },
] as const;
export const sellerPreparationSchema = z.object({
  listing_id: z.string().uuid(),
  completed_steps: z.array(z.enum(["authority", "periods", "reconciliation", "adjustments", "assets", "transfer", "confidentiality", "questions"])).max(8).transform(items => [...new Set(items)]),
});
