import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
const migration=(name:string)=>readFile(new URL(`../supabase/migrations/${name}.sql`,import.meta.url),'utf8');
const buyer='00000000-0000-4000-8000-000000000001',broker='00000000-0000-4000-8000-000000000002',outsider='00000000-0000-4000-8000-000000000003',deal='00000000-0000-4000-8000-000000000004',listing='00000000-0000-4000-8000-000000000005',nda='00000000-0000-4000-8000-000000000006',doc='00000000-0000-4000-8000-000000000007';
test('signing and document sharing enforce authorization, immutability, and atomic evidence',async()=>{
 const db=new PGlite();
 try {
  await db.exec(`create role authenticated;create role anon;create role service_role;create schema auth;create table auth.users(id uuid primary key);
   create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
   create function auth.role() returns text language sql as $$select current_setting('request.jwt.claim.role',true)$$;
   grant usage on schema auth to authenticated,anon;create table public.profiles(user_id uuid primary key,display_name text,locale text);`);
  await db.exec(await migration('0011_marketplace_workspaces'));
  const financial=await migration('0012_automated_nda_and_financial_access');
  await db.exec(financial.slice(0,financial.indexOf('insert into storage.buckets')));
  const trust=await migration('0013_marketplace_trust_and_profiles');
  await db.exec(trust.slice(trust.indexOf('create table if not exists public.marketplace_audit_events'),trust.indexOf('create table if not exists public.marketplace_reports')));
  await db.exec(`alter table deal_room_documents add column if not exists is_active boolean default true,add column if not exists permission_note text;
   alter table marketplace_audit_events enable row level security;grant select,insert on marketplace_audit_events to authenticated;`);
  const guards=await migration('0022_database_authorization_hardening');
  await db.exec(guards.slice(0,guards.indexOf('drop policy if exists "buyers create inquiries"')));
  await db.exec(guards.slice(guards.indexOf('drop policy if exists "participants create notifications"'),guards.indexOf('drop policy if exists "users create reports"')));
  await db.exec(guards.slice(guards.indexOf('create or replace function public.guard_deal_nda_write()'),guards.indexOf('create or replace function public.guard_document_request_update()')));
  await db.exec(await migration('0051_signing_and_document_controls'));
  await db.exec((await migration('0053_nda_audit_fixes')).split('-- NDA_FILE_POLICY:')[0]);
  await db.exec((await migration('0054_signing_workflow')).split('-- DELIVERED_FILE_PROTECTION:')[0]);
  await db.exec(`create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);`);
  await db.exec(await migration('0055_visual_nda_signing'));
  await db.exec(await migration('0056_nda_countersigning'));
  await db.exec(await migration('0058_optional_signing_fields'));
  await db.exec(await migration('0059_signing_decline'));
  await db.exec("alter table listing_nda_templates add column if not exists security_status text default 'basic_validated'");
  await db.exec((await migration('0060_nda_safe_reissue')).split('-- REVISION_FILE_PROTECTION:')[0]);
  await db.exec(`grant all on all tables in schema public to authenticated;
   select set_config('request.jwt.claim.role','service_role',false);
   insert into auth.users values('${buyer}'),('${broker}'),('${outsider}');
   insert into marketplace_listings(id,broker_id,title,summary,industry,city,state_code,status)values('${listing}','${broker}','Test','Test','Test','Test','CA','published');
   insert into deal_inquiries(id,listing_id,buyer_id,broker_id,subject,initial_message,status)values('${deal}','${listing}','${buyer}','${broker}','Test','Test','nda_sent');
   insert into deal_ndas(id,inquiry_id,buyer_id,broker_id,document_name,status,template_version)values('${nda}','${deal}','${buyer}','${broker}','Test','sent',1);
   insert into deal_room_documents(id,inquiry_id,uploaded_by,title,access_level)values('${doc}','${deal}','${broker}','Test','broker_only');`);
  const actor=async(id:string)=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false),set_config('request.jwt.claim.role','authenticated',false)",[id]);await db.exec('set role authenticated');};
  const sign=()=>db.query('select complete_deal_nda($1,$2,1,$3,$4,null,null,$5)',[deal,nda,'Synthetic Buyer','a'.repeat(64),'en']);
  await actor(outsider);await assert.rejects(sign());
  await actor(broker);await assert.rejects(sign());
  await assert.rejects(db.exec(`update deal_ndas set template_body='Changed after delivery' where id='${nda}'`));
  await assert.rejects(db.exec(`update deal_ndas set status='signed',signed_at=now(),signer_name='Forged buyer' where id='${nda}'`), 'Broker must not be able to sign for the buyer');
  await actor(buyer);
  await assert.rejects(db.exec(`update deal_ndas set status='signed',signed_at=now(),signer_name='Synthetic Buyer' where id='${nda}'`), 'Signing must use the atomic evidence workflow');
  const manage=(operation:string,days:number|null=null,reason:string|null=null)=>db.query('select manage_deal_nda($1,1,$2,$3,$4,$5)',[nda,operation,days,reason,'en']);
  await assert.rejects(manage('remind'));await manage('receipt');await manage('receipt');
  assert.equal((await db.query<{n:number}>("select count(*)::int n from deal_nda_events where event_type='receipt_acknowledged'")).rows[0].n,1);
  await assert.rejects(db.query('select complete_deal_nda_core($1,$2,1,$3,$4,null,null,$5)',[deal,nda,'Buyer','a'.repeat(64),'en']));
  await actor(broker);await manage('remind');await assert.rejects(manage('remind'));await manage('expire',1);
  await db.exec(`reset role;update deal_nda_controls set expires_at=now()-interval '1 second' where nda_id='${nda}'`);
  await actor(buyer);await assert.rejects(sign());
  await actor(broker);await manage('expire',0);await manage('withdraw',null,'Synthetic request no longer needed');
  await actor(buyer);await assert.rejects(sign());
  await db.exec(`reset role;delete from deal_nda_controls where nda_id='${nda}'`);
  await actor(buyer);
  await assert.rejects(db.query('select complete_deal_nda($1,$2,2,$3,$4,null,null,$5)',[deal,nda,'Synthetic Buyer','a'.repeat(64),'en']));
  await db.exec('reset role;alter table marketplace_notifications add constraint injected_failure check(false) not valid');
  await actor(buyer);await assert.rejects(sign());
  await db.exec('reset role');
  assert.equal((await db.query<{status:string}>(`select status from deal_ndas where id='${nda}'`)).rows[0].status,'sent');
  await db.exec('alter table marketplace_notifications drop constraint injected_failure');
  await actor(buyer);await sign();await assert.rejects(sign());
  await actor(broker);await assert.rejects(db.exec(`update deal_ndas set signer_name='Changed' where id='${nda}'`));
  const access=(expected:string,next:string)=>db.query('select change_deal_document_access($1,$2,$3)',[doc,expected,next]);
  await actor(buyer);await assert.rejects(access('broker_only','nda_signed'));
  await actor(outsider);await assert.rejects(access('broker_only','nda_signed'));
  await actor(broker);await access('broker_only','nda_signed');await assert.rejects(access('broker_only','approved'));
  await access('nda_signed','broker_only');
  assert.equal((await db.query<{access_level:string}>(`select access_level from deal_room_documents where id='${doc}'`)).rows[0].access_level,'broker_only');
  await actor(buyer);
  assert.equal((await db.query(`select id from deal_room_documents where id='${doc}'`)).rows.length,0);
  await db.exec('reset role');
  assert.equal((await db.query<{n:number}>("select count(*)::int n from marketplace_audit_events where event_type='document_access_changed'")).rows[0].n,2);
  // New visual agreements must use a snapshotted layout and server-produced PDF.
  const visualDeal='00000000-0000-4000-8000-000000000008',visualNda='00000000-0000-4000-8000-000000000009';
  const layout={fields:[{id:doc,type:'signature',page:1,x:.1,y:.1,width:.4,height:.05}],sha256:'b'.repeat(64),pages:1,revision:doc};
  await db.exec(`select set_config('request.jwt.claim.role','service_role',false);insert into listing_nda_templates(listing_id,broker_id,template_body,storage_path,version)values('${listing}','${broker}','Test','synthetic.pdf',1);`);
  await db.query('select save_nda_layout($1,$2,1,$3)',[broker,listing,layout]);
  await db.exec(`insert into deal_inquiries(id,listing_id,buyer_id,broker_id,subject,initial_message,status) values('${visualDeal}','${listing}','${outsider}','${broker}','Test visual','Test','nda_sent');
  insert into deal_ndas(id,inquiry_id,buyer_id,broker_id,document_name,storage_path,status,template_version) values('${visualNda}','${visualDeal}','${outsider}','${broker}','Test','synthetic.pdf','sent',2);`);
  assert.deepEqual((await db.query<{signing_layout:unknown}>(`select signing_layout from deal_ndas where id='${visualNda}'`)).rows[0].signing_layout,layout);
  await actor(outsider);
  await assert.rejects(db.query('select complete_deal_nda($1,$2,2,$3,$4,$5,null,$6)',[visualDeal,visualNda,'Visual Buyer','a'.repeat(64),'b'.repeat(64),'en']));
  const finish=()=>db.query('select complete_visual_nda($1,$2,$3,$4,$5,$6,$7,$8,clock_timestamp(),$9)',[outsider,visualNda,layout,'Visual Buyer','a'.repeat(64),`${visualNda}/synthetic.pdf`,'c'.repeat(64),{[doc]:'Visual Buyer'},'en']);
  await assert.rejects(finish());await assert.rejects(db.query('select save_nda_layout($1,$2,2,$3)',[broker,listing,layout]));
  await actor(broker);await assert.rejects(db.query('update deal_ndas set signing_layout=null where id=$1',[visualNda]));
  await db.exec("reset role;select set_config('request.jwt.claim.role','service_role',false)");
  await db.query('select save_nda_layout($1,$2,2,$3)',[broker,listing,{...layout,revision:nda}]);
  assert.deepEqual((await db.query<{signing_layout:unknown}>(`select signing_layout from deal_ndas where id='${visualNda}'`)).rows[0].signing_layout,layout,'Template changes must not alter a delivered agreement');
  await finish();await assert.rejects(finish());
  assert.equal((await db.query(`select * from deal_nda_pdf_records where nda_id='${visualNda}'`)).rows.length,1);
  await actor(buyer);assert.equal((await db.query(`select * from deal_nda_pdf_records where nda_id='${visualNda}'`)).rows.length,0);
  // A first signature must never release NDA-gated files. Both roles and order
  // are enforced inside one database transaction, not just by the screen.
  for(const [index,order] of ['buyer_first','broker_first','any'].entries()) {
   await db.exec("reset role;select set_config('request.jwt.claim.role','service_role',false)");
   const id=(n:number)=>`00000000-0000-4000-8000-${String(100+index*10+n).padStart(12,'0')}`;
   const l=id(0),d=id(1),n=id(2),f1=id(3),f2=id(4),file=id(5);
   const optional=id(6);
   const dual={...layout,order,fields:[{...layout.fields[0],id:f1,role:'buyer'},{...layout.fields[0],id:f2,role:'broker',y:.3},{...layout.fields[0],id:optional,type:'text',role:'buyer',required:false,y:.5}]};
   await db.query(`insert into marketplace_listings(id,broker_id,title,summary,industry,city,state_code,status)values($1,$2,'Test','Test','Test','Test','CA','published')`,[l,broker]);
   await db.query(`insert into listing_nda_templates(listing_id,broker_id,template_body,storage_path,version,signing_layout) values($1,$2,'Test','synthetic.pdf',1,$3)`,[l,broker,dual]);
   await db.query(`insert into deal_inquiries(id,listing_id,buyer_id,broker_id,subject,initial_message,status)values($1,$2,$3,$4,'Test','Test','nda_sent')`,[d,l,buyer,broker]);
   await db.query(`insert into deal_ndas(id,inquiry_id,buyer_id,broker_id,document_name,storage_path,status,template_version)values($1,$2,$3,$4,'Test','synthetic.pdf','sent',1)`,[n,d,buyer,broker]);
   await db.query(`insert into deal_room_documents(id,inquiry_id,uploaded_by,title,access_level)values($1,$2,$3,'Protected','nda_signed')`,[file,d,broker]);
   const first=order==='broker_first'?broker:buyer,second=first===buyer?broker:buyer;
   const signParty=(who:string,count:number,final=false,values:Record<string,unknown>={...(who===buyer?{[optional]:''}:{}),[who===buyer?f1:f2]:'Synthetic Signer'})=>db.query('select record_nda_signature($1,$2,$3,$4,$5,$6,$7,clock_timestamp(),$8,$9,$10,$11)',[who,n,dual,count,'Synthetic Signer',values,{mode:'typed'},final?`${n}/completed.pdf`:null,final?'c'.repeat(64):null,final?'d'.repeat(64):null,'en']);
   const decline=(who:string,reason='Synthetic signer declines these terms')=>db.query('select decline_nda_request($1,$2,1,$3,$4)',[who,n,reason,'en']);
   await assert.rejects(decline(outsider));await assert.rejects(decline(buyer,'short'));
   await db.exec('begin');await decline(buyer);
   assert.equal((await db.query<{status:string}>('select status from deal_ndas where id=$1',[n])).rows[0].status,'declined');
   assert.equal((await db.query('select * from deal_nda_events where nda_id=$1 and event_type=\'declined\'',[n])).rows.length,1);
   await db.exec('rollback');
   const reissue=(who=broker,version=1,hash='b'.repeat(64))=>db.query('select reissue_nda_request($1,$2,$3,1,$4,$5,$6,$7)',[who,n,version,'Synthetic corrected unsigned request',hash,'b'.repeat(64),'en']);
   await db.query('update listing_nda_templates set broker_attested=true where listing_id=$1',[l]);
   await assert.rejects(reissue(buyer));await assert.rejects(reissue(outsider));await assert.rejects(reissue(broker,2));await assert.rejects(reissue(broker,1,'a'.repeat(64)));
   await db.exec('begin');await db.exec('alter table marketplace_notifications add constraint injected_reissue_failure check(false) not valid');
   await db.exec('savepoint failed_delivery');await assert.rejects(reissue());await db.exec('rollback to failed_delivery');
   assert.equal((await db.query('select * from deal_nda_revisions where nda_id=$1',[n])).rows.length,0,'Failed notification must roll back archival and replacement together');
   assert.equal((await db.query<{template_version:number}>('select template_version from deal_ndas where id=$1',[n])).rows[0].template_version,1);
   await db.exec('rollback');
   await db.exec('begin');
   await reissue();
   const replaced=(await db.query<{template_version:number;signing_layout:typeof dual}>('select template_version,signing_layout from deal_ndas where id=$1',[n])).rows[0];
   assert.equal(replaced.template_version,2);assert.notEqual(replaced.signing_layout.revision,dual.revision);
   const archive=(await db.query<{agreement:{signing_layout:typeof dual}}>('select agreement from deal_nda_revisions where nda_id=$1',[n])).rows[0];assert.deepEqual(archive.agreement.signing_layout,dual);
   await db.exec('savepoint stale_sign');await assert.rejects(signParty(first,0),'Stale layout must not sign the replacement');await db.exec('rollback to stale_sign');
   await db.exec('savepoint stale_reissue');await assert.rejects(reissue(),'A repeated stale reissue cannot create another revision');await db.exec('rollback to stale_reissue');
   await actor(outsider);assert.equal((await db.query('select * from deal_nda_revisions where nda_id=$1',[n])).rows.length,0);
   await actor(buyer);assert.equal((await db.query('select * from deal_nda_revisions where nda_id=$1',[n])).rows.length,1);
   assert.equal((await db.query("update deal_nda_revisions set reason='Forged history' where nda_id=$1 returning id",[n])).rows.length,0,'RLS must prevent history edits');
   await db.exec('rollback');await db.exec("reset role;select set_config('request.jwt.claim.role','service_role',false)");
   if(order!=='any')await assert.rejects(signParty(second,0));
   await assert.rejects(signParty(outsider,0));
   await assert.rejects(signParty(first,0,false,{[first===buyer?f1:f2]:null}));
   await assert.rejects(signParty(first,0,false,{[f1]:'Forged',[f2]:'Forged'}));
   await assert.rejects(db.query('select complete_visual_nda($1,$2,$3,$4,$5,$6,$7,$8,clock_timestamp(),$9)',[buyer,n,dual,'Buyer','a'.repeat(64),`${n}/x.pdf`,'c'.repeat(64),{[f1]:'Buyer',[f2]:'Broker'},'en']));
   await signParty(first,0);
   await assert.rejects(reissue(),'Even one recorded signature must block reissue');
   await assert.rejects(decline(first),'Recorded signatures cannot be retracted through decline');
   assert.equal((await db.query<{status:string}>('select status from deal_ndas where id=$1',[n])).rows[0].status,'sent');
   assert.equal((await db.query('select * from deal_nda_pdf_records where nda_id=$1',[n])).rows.length,0);
   await assert.rejects(signParty(first,1));await assert.rejects(signParty(second,0,true));
   await actor(buyer);assert.equal((await db.query('select * from deal_room_documents where id=$1',[file])).rows.length,0);
   await assert.rejects(signParty(second,1,true));
   await actor(outsider);assert.equal((await db.query('select * from deal_nda_signatures where nda_id=$1',[n])).rows.length,0);
   await db.exec("reset role;select set_config('request.jwt.claim.role','service_role',false)");
   await db.query('insert into deal_nda_controls(nda_id,expires_at)values($1,now()-interval \'1 second\')',[n]);
   await assert.rejects(signParty(second,1,true));
   await db.query('delete from deal_nda_controls where nda_id=$1',[n]);
   await assert.rejects(signParty(second,1,false));
   assert.equal((await db.query('select * from deal_nda_signatures where nda_id=$1',[n])).rows.length,1,'Failed completion rolls back second signature');
   await signParty(second,1,true);
   assert.equal((await db.query<{status:string}>('select status from deal_ndas where id=$1',[n])).rows[0].status,'signed');
   assert.equal((await db.query('select * from deal_nda_signatures where nda_id=$1',[n])).rows.length,2);
   await actor(buyer);assert.equal((await db.query('select * from deal_room_documents where id=$1',[file])).rows.length,1);
  }
  await db.exec("reset role;select set_config('request.jwt.claim.role','service_role',false)");
  for(let i=0;i<20;i++)await db.query('select save_nda_preset($1,$2,$3)',[broker,`Preset ${i}`,layout]);
  await assert.rejects(db.query('select save_nda_preset($1,$2,$3)',[broker,'Overflow',layout]));
  await db.query('select save_nda_preset($1,$2,$3)',[broker,'Preset 0',layout]);
  await actor(outsider);assert.equal((await db.query('select * from nda_layout_presets')).rows.length,0);
  await assert.rejects(db.query('select save_nda_preset($1,$2,$3)',[broker,'Forged',layout]));
 } finally {await db.close();}
});
