import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
const migration=(name:string)=>readFile(new URL(`../supabase/migrations/${name}.sql`,import.meta.url),'utf8');
const buyer='00000000-0000-4000-8000-000000000001',broker='00000000-0000-4000-8000-000000000002',outsider='00000000-0000-4000-8000-000000000003',deal='00000000-0000-4000-8000-000000000004',listing='00000000-0000-4000-8000-000000000005',nda='00000000-0000-4000-8000-000000000006',doc='00000000-0000-4000-8000-000000000007';
test('signing and document sharing enforce authorization, immutability, and atomic evidence',async()=>{
 const db=new PGlite();
 try {
  await db.exec(`create role authenticated;create role anon;create role service_role;create schema auth;create table auth.users(id uuid primary key);
   create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
   create function auth.role() returns text language sql as $$select current_setting('request.jwt.claim.role',true)$$;
   grant usage on schema auth to authenticated,anon;create table public.profiles(user_id uuid primary key,display_name text,locale text);`);
  await db.exec(await migration('0011_marketplace_workspaces'));
  const financial=await migration('0012_automated_nda_and_financial_access');
  await db.exec(financial.slice(0,financial.indexOf('insert into storage.buckets')));
  const trust=await migration('0013_marketplace_trust_and_profiles');
  await db.exec(trust.slice(trust.indexOf('create table if not exists public.marketplace_audit_events'),trust.indexOf('create table if not exists public.marketplace_reports')));
  await db.exec(`alter table deal_room_documents add column if not exists is_active boolean default true,add column if not exists permission_note text;
   alter table marketplace_audit_events enable row level security;grant select,insert on marketplace_audit_events to authenticated;`);
  const guards=await migration('0022_database_authorization_hardening');
  await db.exec(guards.slice(0,guards.indexOf('drop policy if exists "buyers create inquiries"')));
  await db.exec(guards.slice(guards.indexOf('drop policy if exists "participants create notifications"'),guards.indexOf('drop policy if exists "users create reports"')));
  await db.exec(guards.slice(guards.indexOf('create or replace function public.guard_deal_nda_write()'),guards.indexOf('create or replace function public.guard_document_request_update()')));
  await db.exec(await migration('0051_signing_and_document_controls'));
  await db.exec((await migration('0053_nda_audit_fixes')).split('-- NDA_FILE_POLICY:')[0]);
  await db.exec((await migration('0054_signing_workflow')).split('-- DELIVERED_FILE_PROTECTION:')[0]);
  await db.exec(`grant all on all tables in schema public to authenticated;
   select set_config('request.jwt.claim.role','service_role',false);
   insert into auth.users values('${buyer}'),('${broker}'),('${outsider}');
   insert into marketplace_listings(id,broker_id,title,summary,industry,city,state_code,status)values('${listing}','${broker}','Test','Test','Test','Test','CA','published');
   insert into deal_inquiries(id,listing_id,buyer_id,broker_id,subject,initial_message,status)values('${deal}','${listing}','${buyer}','${broker}','Test','Test','nda_sent');
   insert into deal_ndas(id,inquiry_id,buyer_id,broker_id,document_name,status,template_version)values('${nda}','${deal}','${buyer}','${broker}','Test','sent',1);
   insert into deal_room_documents(id,inquiry_id,uploaded_by,title,access_level)values('${doc}','${deal}','${broker}','Test','broker_only');`);
  const actor=async(id:string)=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false),set_config('request.jwt.claim.role','authenticated',false)",[id]);await db.exec('set role authenticated');};
  const sign=()=>db.query('select complete_deal_nda($1,$2,1,$3,$4,null,null,$5)',[deal,nda,'Synthetic Buyer','a'.repeat(64),'en']);
  await actor(outsider);await assert.rejects(sign());
  await actor(broker);await assert.rejects(sign());
  await assert.rejects(db.exec(`update deal_ndas set template_body='Changed after delivery' where id='${nda}'`));
  await assert.rejects(db.exec(`update deal_ndas set status='signed',signed_at=now(),signer_name='Forged buyer' where id='${nda}'`), 'Broker must not be able to sign for the buyer');
  await actor(buyer);
  await assert.rejects(db.exec(`update deal_ndas set status='signed',signed_at=now(),signer_name='Synthetic Buyer' where id='${nda}'`), 'Signing must use the atomic evidence workflow');
  const manage=(operation:string,days:number|null=null,reason:string|null=null)=>db.query('select manage_deal_nda($1,1,$2,$3,$4,$5)',[nda,operation,days,reason,'en']);
  await assert.rejects(manage('remind'));await manage('receipt');await manage('receipt');
  assert.equal((await db.query<{n:number}>("select count(*)::int n from deal_nda_events where event_type='receipt_acknowledged'")).rows[0].n,1);
  await assert.rejects(db.query('select complete_deal_nda_core($1,$2,1,$3,$4,null,null,$5)',[deal,nda,'Buyer','a'.repeat(64),'en']));
  await actor(broker);await manage('remind');await assert.rejects(manage('remind'));await manage('expire',1);
  await db.exec(`reset role;update deal_nda_controls set expires_at=now()-interval '1 second' where nda_id='${nda}'`);
  await actor(buyer);await assert.rejects(sign());
  await actor(broker);await manage('expire',0);await manage('withdraw',null,'Synthetic request no longer needed');
  await actor(buyer);await assert.rejects(sign());
  await db.exec(`reset role;delete from deal_nda_controls where nda_id='${nda}'`);
  await actor(buyer);
  await assert.rejects(db.query('select complete_deal_nda($1,$2,2,$3,$4,null,null,$5)',[deal,nda,'Synthetic Buyer','a'.repeat(64),'en']));
  await db.exec('reset role;alter table marketplace_notifications add constraint injected_failure check(false) not valid');
  await actor(buyer);await assert.rejects(sign());
  await db.exec('reset role');
  assert.equal((await db.query<{status:string}>(`select status from deal_ndas where id='${nda}'`)).rows[0].status,'sent');
  await db.exec('alter table marketplace_notifications drop constraint injected_failure');
  await actor(buyer);await sign();await assert.rejects(sign());
  await actor(broker);await assert.rejects(db.exec(`update deal_ndas set signer_name='Changed' where id='${nda}'`));
  const access=(expected:string,next:string)=>db.query('select change_deal_document_access($1,$2,$3)',[doc,expected,next]);
  await actor(buyer);await assert.rejects(access('broker_only','nda_signed'));
  await actor(outsider);await assert.rejects(access('broker_only','nda_signed'));
  await actor(broker);await access('broker_only','nda_signed');await assert.rejects(access('broker_only','approved'));
  await access('nda_signed','broker_only');
  assert.equal((await db.query<{access_level:string}>(`select access_level from deal_room_documents where id='${doc}'`)).rows[0].access_level,'broker_only');
  await actor(buyer);
  assert.equal((await db.query(`select id from deal_room_documents where id='${doc}'`)).rows.length,0);
  await db.exec('reset role');
  assert.equal((await db.query<{n:number}>("select count(*)::int n from marketplace_audit_events where event_type='document_access_changed'")).rows[0].n,2);
 } finally {await db.close();}
});
