import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
test('email outbox isolates recipients, reserves free quotas, recovers leases and cancels stale requests',async()=>{
 const db=new PGlite();
 try{
  await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key);
   create table deal_ndas(id uuid primary key,inquiry_id uuid,buyer_id uuid,broker_id uuid,status text,signing_layout jsonb);
   create table deal_nda_controls(nda_id uuid,withdrawn_at timestamptz,expires_at timestamptz);
   create table marketplace_notifications(id uuid primary key default gen_random_uuid(),user_id uuid,inquiry_id uuid,kind text,href text);`);
  await db.exec(await readFile(new URL('../supabase/migrations/0057_signing_email_outbox.sql',import.meta.url),'utf8'));
  const ids=(await db.query<{a:string;b:string;n:string;i:string}>('select gen_random_uuid() a,gen_random_uuid() b,gen_random_uuid() n,gen_random_uuid() i')).rows[0];
  await db.query('insert into auth.users values($1),($2)',[ids.a,ids.b]);
  await db.query("insert into deal_ndas values($1,$2,$3,$4,'sent',null)",[ids.n,ids.i,ids.a,ids.b]);
  await db.query("insert into marketplace_notifications(user_id,inquiry_id,kind,href)values($1,$2,'nda_sent','/es/dashboard')",[ids.a,ids.i]);
  const row=(await db.query<{id:string;locale:string}>('select * from signing_email_outbox')).rows[0];assert.equal(row.locale,'en');
  assert.equal((await db.query('select * from signing_email_outbox')).rows.length,1,'Invitation is queued atomically, not duplicated by an in-app notice');
  await db.exec('set role authenticated');await assert.rejects(db.exec('select * from signing_email_outbox'));await assert.rejects(db.exec('select * from claim_signing_emails()'));await db.exec('reset role');
  assert.equal((await db.query('select * from claim_signing_emails(5)')).rows.length,1);
  assert.equal((await db.query('select * from claim_signing_emails(5)')).rows.length,0);
  await db.exec("update signing_email_outbox set lease_until=now()-interval '1 minute'");
  assert.equal((await db.query('select * from claim_signing_emails(5)')).rows.length,1);
  await db.query('insert into deal_nda_controls values($1,now(),null)',[ids.n]);
  await db.exec('select * from claim_signing_emails(5)');
  assert.equal((await db.query<{state:string}>('select state from signing_email_outbox where id=$1',[row.id])).rows[0].state,'cancelled');
  await db.query("update deal_ndas set status='signed' where id=$1",[ids.n]);
  assert.equal((await db.query("select * from signing_email_outbox where kind='completed'")).rows.length,2);
  await db.query("update deal_ndas set status='signed' where id=$1",[ids.n]);
  assert.equal((await db.query("select * from signing_email_outbox where kind='completed'")).rows.length,2);
  await db.exec("update signing_email_outbox set first_attempt_at=now()-interval '24 hours' where kind='completed';select * from claim_signing_emails()");
  assert.equal((await db.query("select * from signing_email_outbox where state='failed' and last_error='reconciliation_required'")).rows.length,2);
  await db.query("insert into signing_email_outbox(nda_id,recipient_id,kind,event_key,first_attempt_at,state)select $1,$2,'completed','quota:'||g,now(),'sent' from generate_series(1,90) g",[ids.n,ids.a]);
  await db.query("insert into signing_email_outbox(nda_id,recipient_id,kind,event_key)values($1,$2,'completed','blocked-quota')",[ids.n,ids.a]);
  assert.equal((await db.query('select * from claim_signing_emails()')).rows.length,0);
  const provider='00000000-0000-4000-8000-000000000099';
  await db.query("update signing_email_outbox set provider_id=$1,state='sent' where id=$2",[provider,row.id]);
  const delivery=(id:string,state:string,code:string)=>db.query('select record_signing_delivery($1,$2,$3,now(),$4) ok',[id,provider,state,code]);
  await delivery('delivered-1','delivered','email.delivered');
  await delivery('delivered-1','delivered','email.delivered');
  assert.equal((await db.query("select * from signing_email_delivery_events")).rows.length,1);
  await delivery('bounce-1','failed','email.bounced');await delivery('delivered-late','delivered','email.delivered');
  assert.equal((await db.query<{state:string}>('select state from signing_email_outbox where id=$1',[row.id])).rows[0].state,'failed');
  assert.equal((await db.query<{ok:boolean}>("select record_signing_delivery('unknown','unknown','delivered',now(),'email.delivered') ok")).rows[0].ok,false);
  await assert.rejects(db.exec('select * from claim_signing_emails(1000)'));
 }finally{await db.close();}
});
