import Link from 'next/link';
import {notFound,redirect} from 'next/navigation';
import {PlatformShell,PageHeading} from '@/components/platform-shell';
import {isLocale} from '@/lib/i18n';
import {createSupabaseServerClient} from '@/lib/supabase/server';
import {createSupabaseAdminClient} from '@/lib/supabase/admin';
import {evidenceOperation} from './actions';
import '../operations/workforce-operations.css';

export default async function Evidence({params,searchParams}:{params:Promise<{locale:string}>;searchParams:Promise<{owner?:string;task?:string;notice?:string}>}) {
  const {locale}=await params;if(!isLocale(locale))notFound();const t=(en:string,es:string)=>locale==='es'?es:en;
  const db=await createSupabaseServerClient();const {data:{user}}=await db.auth.getUser();if(!user)redirect(`/${locale}/sign-in`);
  const q=await searchParams,owner=q.owner||user.id;
  const role=await db.rpc('workforce_role',{p_owner:owner});
  const tasks=await db.from('workforce_tasks').select('id,employee_id,title,status,version,assignee_id').eq('owner_id',owner).eq('category','training').order('created_at',{ascending:false}).limit(100);
  const selected=q.task?await db.from('workforce_tasks').select('id,employee_id,title,status,version,assignee_id').eq('owner_id',owner).eq('category','training').eq('id',q.task).maybeSingle():null;
  // Only this authenticated uploader's own vault candidates. Never list the
  // employer's private vault merely because the viewer has an HR membership.
  const documents=await createSupabaseAdminClient().from('vault_documents').select('id,original_name').eq('owner_id',user.id).in('security_status',['basic_validated','malware_scanned']).not('scan_sha256','is',null).order('updated_at',{ascending:false}).limit(100);
  const links=selected?.data?await db.from('workforce_training_evidence').select('id,original_name,shared_by,shared_at,revoked_at,revoke_reason').eq('task_id',selected.data.id).order('shared_at',{ascending:false}).limit(100):null;
  const employee=selected?.data?await db.from('employees').select('full_name').eq('id',selected.data.employee_id).maybeSingle():null;
  const availability=await Promise.all((links?.data??[]).map(async a=>({id:a.id,...await db.rpc('workforce_training_evidence_available',{p_evidence:a.id})})));
  const failed=role.error||tasks.error||selected?.error||documents.error||links?.error||employee?.error||availability.some(a=>a.error);
  const canShare=selected?.data?.status==='open'&&(['owner','hr','manager'].includes(role.data??'')||selected?.data?.assignee_id===user.id);
  const hidden=<><input name="locale" type="hidden" value={locale}/><input name="owner" type="hidden" value={owner}/><input name="task" type="hidden" value={selected?.data?.id??''}/></>;
  return <PlatformShell locale={locale} active="workforce"><div className="dashboard-content wf-ops"><PageHeading eyebrow={t('People operations','Operaciones de personal')} title={t('Training evidence','Evidencia de capacitación')} body={t('Explicit file sharing for individual training tasks.','Archivos compartidos explícitamente para tareas de capacitación individuales.')} action={<Link href={`/${locale}/dashboard/workforce/operations?owner=${encodeURIComponent(owner)}`}>{t('Command center','Centro de operaciones')}</Link>}/>
    <p>{t('Upload a certificate through your existing private document vault, then explicitly attach it to a task here. Only this employee and their currently authorized owner, HR and assigned manager can access the attachment. No other vault files are shared.','Carga un certificado en tu bóveda privada y adjúntalo explícitamente a una tarea aquí. Solo este empleado y su propietario, RR. HH. y gerente asignado autorizados pueden acceder. No se comparten otros archivos de la bóveda.')}</p><Link href={`/${locale}/dashboard/documents`}>{t('Open my private document vault','Abrir mi bóveda privada')}</Link>
    {q.notice&&<p role={q.notice==='saved'?'status':'alert'}>{q.notice==='saved'?t('Evidence sharing updated.','Archivos compartidos actualizados.'):t('Not saved. Refresh and check task status, file screening, ownership and access.','No guardado. Actualiza y revisa estado de tarea, análisis del archivo, propiedad y acceso.')}</p>}
    {failed?<p role="alert">{t('Training evidence could not load. Refresh before changing shares.','No se pudo cargar la evidencia. Actualiza antes de cambiar archivos compartidos.')}</p>:<><section className="panel"><h2>{t('Choose a training task','Elegir tarea de capacitación')}</h2><ul>{tasks.data?.map(task=><li key={task.id}><Link href={`/${locale}/dashboard/workforce/evidence?owner=${encodeURIComponent(owner)}&task=${task.id}`}>{task.title}</Link></li>)}</ul>{!tasks.data?.length&&<p>{t('No training tasks available. Create or request an assignment in the command center.','No hay tareas disponibles. Crea o solicita una asignación en el centro de operaciones.')}</p>}{tasks.data?.length===100&&<p>{t('Showing the latest 100 tasks.','Se muestran las últimas 100 tareas.')}</p>}</section>
    {selected?.data&&<section className="panel"><h2>{selected.data.title}</h2><p>{t('Employee','Empleado')}: {employee?.data?.full_name}</p><p>{t('Attachment sharing does not complete or verify training. Replacing or deleting the source file disables this link. Previously downloaded copies cannot be recalled.','Compartir no completa ni verifica la capacitación. Reemplazar o eliminar el archivo de origen desactiva el enlace. No se pueden recuperar copias ya descargadas.')}</p>
      {canShare&&<form action={evidenceOperation}>{hidden}<input name="operation" type="hidden" value="share"/><input name="version" type="hidden" value={selected.data.version}/><label>{t('My screened file','Mi archivo revisado')}<select name="document" required><option value="">{t('Choose a file','Elegir archivo')}</option>{documents.data?.map(d=><option key={d.id} value={d.id}>{d.original_name}</option>)}</select></label>{documents.data?.length===100&&<p>{t('Showing the latest 100 screened files.','Se muestran los últimos 100 archivos revisados.')}</p>}<label><input name="confirmed" type="checkbox" value="yes" required/>{t('I reviewed the file and authorize sharing this version with the employee and their authorized reviewers.','Revisé el archivo y autorizo compartir esta versión con el empleado y sus revisores autorizados.')}</label><button>{t('Share file with this task','Compartir archivo con esta tarea')}</button></form>}
      <h3>{t('Attached evidence','Evidencia adjunta')}</h3>{!links?.data?.length&&<p>{t('No files attached.','Sin archivos adjuntos.')}</p>}{links?.data?.map(a=><article key={a.id}><h4>{a.original_name}</h4>{availability.find(x=>x.id===a.id)?.data===true?<a href={`/api/workforce/evidence/${a.id}`}>{t('Download reviewed version','Descargar versión revisada')}</a>:<p>{t('Unavailable: revoked, replaced, deleted, archived or no longer cleared for download.','No disponible: revocado, reemplazado, eliminado, archivado o sin autorización de descarga.')}</p>}{a.revoke_reason&&<p>{a.revoke_reason}</p>}{!a.revoked_at&&(a.shared_by===user.id||['owner','hr'].includes(role.data??''))&&<details><summary>{t('Revoke sharing','Revocar acceso')}</summary><form action={evidenceOperation}>{hidden}<input name="operation" type="hidden" value="revoke"/><input name="evidence" type="hidden" value={a.id}/><label>{t('Reason','Motivo')}<textarea name="reason" required maxLength={1000}/></label><label><input name="confirmed" type="checkbox" value="yes" required/>{t('Stop future downloads through this link.','Impedir futuras descargas por este enlace.')}</label><button>{t('Revoke link','Revocar enlace')}</button></form></details>}</article>)}{links?.data?.length===100&&<p>{t('Showing the latest 100 attachment records.','Se muestran los últimos 100 registros de archivos.')}</p>}
    </section>}</>}
  </div></PlatformShell>;
}
